import { join } from 'node:path';
import { type Composition } from '../composition.js';
import { VERSION } from '../version.js';
import { type ProjectContext, writeFileRecursive } from './_shared.js';

export async function writeDocs(ctx: ProjectContext, composition: Composition): Promise<void> {
  const { targetDir } = ctx;
  const isTs = composition.backend === 'ts';
  const isMicroservices = composition.topology === 'microservices';
  const isMobileOn = composition.mobile !== 'none';
  const mobileVariant = composition.mobile === 'flutter' ? 'flutter' : 'expo';
  const isAiOn = composition.ai === 'on';

  await writeFileRecursive(
    join(targetDir, 'docs/architecture/contract-spine.md'),
    isTs ? contractSpineTsMd(isMicroservices, isMobileOn) : contractSpineGoMd(isMobileOn, mobileVariant),
  );
  await writeFileRecursive(
    join(targetDir, 'docs/architecture/modular-monolith.md'),
    modularMonolithMd(isMicroservices),
  );
  await writeFileRecursive(
    join(targetDir, 'docs/architecture/auth-subtree.md'),
    authSubtreeMd(isMicroservices, isMobileOn, mobileVariant),
  );
  await writeFileRecursive(
    join(targetDir, 'docs/architecture/typed-rpc-transport.md'),
    isTs ? typedRpcTransportTsMd(isMicroservices) : typedRpcTransportGoMd(),
  );

  await writeFileRecursive(join(targetDir, 'docs/wire-it-in/auth.md'), wireItInAuthMd());
  if (isAiOn) {
    await writeFileRecursive(join(targetDir, 'docs/wire-it-in/ai.md'), wireItInAiMd());
  }

  await writeFileRecursive(join(targetDir, 'docs/adr/README.md'), adrReadmeMd());

  // Decision 38 — the second release-note artifact: docs/migrations/.
  // The scaffolded project receives the migration notes that APPLY to
  // the Starter version that generated it (the lookup mechanism below).
  // Pre-1.0 the lookup is empty (every change is breaking, decision 35
  // — re-scaffold, no recipes), so the scaffold ships the convention
  // README only, no notes.
  const migrationNotes = migrationNotesFor(VERSION);
  await writeFileRecursive(
    join(targetDir, 'docs/migrations/README.md'),
    migrationsReadmeMd(VERSION),
  );
  for (const [fileName, content] of migrationNotes) {
    await writeFileRecursive(join(targetDir, 'docs/migrations/', fileName), content);
  }

  await writeFileRecursive(join(targetDir, 'docs/standards/code-style.md'),
    isTs ? codeStyleTsMd() : codeStyleGoMd());
  await writeFileRecursive(join(targetDir, 'docs/standards/best-practices.md'), bestPracticesMd(isMicroservices));
  await writeFileRecursive(join(targetDir, 'docs/standards/anti-patterns.md'), antiPatternsMd());
  if (isMobileOn) {
    await writeFileRecursive(
      join(targetDir, 'docs/architecture/mobile-auth-flow.md'),
      mobileAuthFlowMd(isMicroservices, mobileVariant),
    );
  }
}

// migrationNotesFor returns the migration notes the scaffolded project
// must receive, given the Starter version that generated it (decision
// 38's lookup mechanism, keyed on starterVersion).
//
// Post-1.0, when a breaking change ships, the maintainer adds a
// `docs/migrations/vX-to-vY.md` recipe to the Starter repo AND an entry
// here mapping it to the versions it applies to; the scaffolded project
// then receives the recipes whose range covers its starterVersion.
//
// Pre-1.0 (the phase this Starter is in): every change is breaking and
// users re-scaffold to upgrade (decision 35), so there are no migration
// notes — the lookup returns an empty list and the scaffold ships the
// CHANGELOG only.
function migrationNotesFor(_starterVersion: string): Array<[fileName: string, content: string]> {
  return [];
}

function migrationsReadmeMd(starterVersion: string): string {
  return `# Migration notes

This directory holds **how** to upgrade past a breaking change in the
[create-fs-starter](https://github.com/Johna210/starter) release that
generated this project (decision 38 — the second of the two release-note
artifacts; the CHANGELOG records *what* changed, these recipes record
*how* to upgrade).

- One file per version transition: \`v1.2-to-v1.3.md\`.
- Structure: \`what changed\` (1–2 paragraphs) → \`if you're on X\`
  (steps) → \`if you're on Y\` (steps) → \`verify\` (what to check
  after the upgrade).
- Linked from the CHANGELOG entry for the breaking release.

**This project is pre-1.0** (generated by create-fs-starter
v${starterVersion}): every Starter change is breaking (decision 35) and the
expected upgrade path is to **re-scaffold** — there are no migration
notes yet. Post-1.0, the notes that apply to this project's
\`starterVersion\` are materialized into this directory automatically.
`;
}

function wireItInAuthMd(): string {
  return `# Auth: what's in the shim, what isn't

The starter ships an \`auth shim\` (decision 12) — a *thin typed layer*
over vetted upstream libraries that owns the **surface** of auth
(token shape, argon2id parameters, the four HTTP endpoints, refresh
rotation). It does **not** ship everything you might want from a
real auth system; the rest is fenced off below as "wire it in: here's
the seam."

## What the shim ships

- **Password hashing**: \`hashPassword\` / \`verifyPassword\` (argon2id
  via the canonical \`argon2\` Node bindings, OWASP 2024 parameters).
- **JWT issue/verify**: \`signToken\` / \`verifyToken\` (HS256 via
  \`jose\`).
- **Refresh-token rotation**: \`issueTokenPair\` / \`rotateTokenPair\` /
  \`revokeRefreshToken\`, over a \`RefreshTokenStore\` seam.
- **Four HTTP endpoints** (\`/auth/{register,login,refresh,logout}\`)
  with zod-validated input and JSON output.
- **Sole-minter invariant** (decision 11): only \`apps/api\` reads
  \`JWT_SECRET\`. No other service in the monorepo holds a signing key.

Real libraries, not mocks. The \`@starter/auth\` package's unit tests
exercise \`argon2\`, \`jose\`, and the rotation store against real
implementations (decision 22).

## What the shim does NOT ship (the fences)

These are intentionally out of scope. Each is a real product decision
that varies per app — shipping one would be a bait-and-switch (decision 12).
For each, the seam is the \`@starter/auth\` package; the api's
\`internal/auth/\` module is the HTTP boundary; and \`apps/api\` is the
deployment surface.

### Email verification

Send a one-time link after \`/auth/register\`; the user clicks to mark
their email as verified. **Seam**: add a \`users.emailVerifiedAt\`
column to \`packages/db\` (migration 0003), then a new \`/auth/verify\`
route that flips it on a valid token. \`@starter/auth\` exports the
token shape; you add the mailer and the route. The login response can
include \`{ emailVerified: boolean }\` and the api can 403 unverified
users on a per-project policy.

### Password reset

\`POST /auth/forgot-password { email }\` emails a short-lived token;
\`POST /auth/reset-password { token, newPassword }\` validates and
updates. **Seam**: a new \`password_reset_tokens\` table in
\`packages/db\` (parallel to \`refresh_tokens\`), a new store
implementation in \`apps/api/src/internal/auth/\`, two new routes on
the auth sub-router. The \`hashPassword\` function in
\`@starter/auth\` is the password-update primitive.

### MFA (TOTP, WebAuthn, SMS)

Step-up auth: after password login, a second factor. **Seam**: add a
\`user_factors\` table (factor type, public key / secret, last used
counter), a \`/auth/mfa/*\` route group, and a per-project policy
in \`apps/api\` (which routes require step-up). The lib's
\`signToken\` / \`verifyToken\` stay unchanged — you can issue
short-lived step-up tokens with a custom payload field.

### OAuth / social login (Google, GitHub, etc.)

\`POST /auth/oauth/{provider}/callback { code }\` exchanges an auth
code for a user identity, then either finds-or-creates a row in
\`users\`, then issues a token pair. **Seam**: add a per-provider
config block (\`GOOGLE_CLIENT_ID\`, \`GOOGLE_CLIENT_SECRET\`, ...) to
\`apps/api/src/config.ts\`; a new \`oauth_accounts\` table linking
provider+subject to userId; the existing \`issueTokenPair\` handles
the rest. The web client redirects; the api handles the callback.

### RBAC (roles, permissions, organizations)

Beyond "a single authenticated principal", role/permission checks
(\`role: 'admin'\`, \`can('items:write')\`, etc.) are per-domain. **Seam**:
add the columns/tables you need to \`packages/db\` (e.g.
\`user_roles(user_id, role)\`), a \`requireRole(...)\` middleware
parallel to \`requireAuth\` in \`apps/api/src/internal/auth/\`, and
apply it to the routes that need it. The base \`requireAuth\` is
unchanged — the \`userId\` it sets on the context is the FK into
your role tables.

## Why these are fences, not features

Decision 12 (locked): the starter owns the surface, not the entire
auth system. A "real minimal auth" is a contradiction — real auth has
no minimum, and shipping one turns the starter into a *maintained
auth framework* (every CVE, every rotation bug lands forever). A
"documented stub" is the bait-and-switch rejected at the architecture
level in decision 10. Fences are the third path: the seam is real,
the shim is honest, the rest is a deliberate handoff.
`;
}

function wireItInAiMd(): string {
  return `# Wire it in: AI

The AI fence is **on** for this composition (issue #17): \`packages/ai\`
ships the composable AI primitives of decision 20 — chat completion
(with streaming), embeddings, a \`VectorStore\` interface (pgvector
default over the db's \`embeddings\` table, decision 14 reuse), and
tool/function calling. Each primitive is a real typed layer over the
\`openai\` SDK, not a stub. **No example composition is shipped**
(decision 20): these are the building blocks — composing them into a
product (RAG, recommendation, agentic) is your job.

## What the scaffold ships

\`packages/ai/src/\`:

- \`chat.ts\` — \`chatComplete(messages, opts)\`; \`opts.stream: true\`
  returns an \`AsyncIterable\` of \`ChatChunk\` (SSE-style deltas)
- \`embeddings.ts\` — \`embed(texts)\` returns vectors for retrieval
- \`vector-store.ts\` — the \`VectorStore\` interface, a pure
  \`cosineSimilarity\`, and \`PgVectorStore\` (upserts into the db's
  \`embeddings\` table, cosine search via \`<=>\`)
- \`tool-call.ts\` — \`toolCall(tools, message)\` + \`ToolRegistry\`
  (register a tool, let the model call it, run it)
- \`config.ts\` — zod-validated \`readAiConfig()\` (decision 28):
  \`OPENAI_API_KEY\`, \`OPENAI_BASE_URL\`, \`OPENAI_MODEL\` (default
  \`gpt-4o-mini\`), \`OPENAI_EMBEDDINGS_MODEL\` (default
  \`text-embedding-3-small\`)
- \`fakes.ts\` — \`FakeProvider\`, the seam the unit tests exercise
  (decision 29: a mocked-LLM round-trip is a unit test, not CI)

Unit tests ship for each primitive (decision 22) and run via
\`task test:ai\`. The workspace is **NOT CI-tested** (decisions 24/29:
generatable, not blessed) — run them locally.

## How to wire it in

1. Set \`OPENAI_API_KEY\` in \`packages/ai/.env\` (copy
   \`packages/ai/.env.example\`); optional: \`OPENAI_BASE_URL\` (any
   OpenAI-compatible endpoint), \`OPENAI_MODEL\` /
   \`OPENAI_EMBEDDINGS_MODEL\` / \`OPENAI_TIMEOUT_SECONDS\`.
2. \`task migrate\` — the 0003_embeddings migration (installed with the
   AI-on scaffold) creates the \`embeddings\` table + pgvector index.
3. Call the primitives where your product needs them — e.g. embed your
   rows into \`PgVectorStore\` on write, \`search()\` on read; or hand
   \`toolCall()\` your app's functions and let the model dispatch.

The fence is the primitive surface: the starter owns the typed seams
over the provider; you own the composition.
`;
}

function contractSpineTsMd(isMicroservices: boolean, isMobileOn = false): string {
  const mobileDescription = isMobileOn
    ? '\n\nThe Expo peer app in apps/mobile consumes the same Hono RPC client as the web. It calls the API directly, stores auth tokens through expo-secure-store, and never introduces a second domain-types package.'
    : '';
  const mobileDiagramMicroservices = isMobileOn
    ? '\n    subgraph "apps/mobile (Expo)"\n        MOBILE["login + items screens"]\n        MC["@starter/api-client"]\n    end\n    MOBILE -->|typed call| MC\n    MC -->|HTTP + Bearer| R1\n'
    : '';
  const mobileDiagramMonolith = isMobileOn
    ? '\n    subgraph "apps/mobile (Expo)"\n        MOBILE["login + items screens"]\n        MC["@starter/api-client"]\n    end\n    MOBILE -->|typed call| MC\n    MC -->|HTTP + Bearer| R\n'
    : '';
  if (isMicroservices) {
    return `# Your Hono RPC contract spine (TS-microservices)

This is your contract spine: the API agreement between \`apps/web\` and
the backend services in this **TS-microservices** scaffold (decisions 3,
9, 17, 18, 10, 11).

## How it works

In TS-only shapes (this one), the contract is **implicit** — shared TS
types, no artifact. The api framework is **Hono** (decision 18), so the
contract mechanism is **Hono RPC** (\`hc<typeof app>()\`): each router's
TS type *is* the wire contract, inferred end-to-end (inputs, outputs,
error shapes), no codegen, no separate source of truth to drift.

There are **two** services in this shape (decision 10's example split):

- \`apps/api\` — main API; mounts \`/items\`; verifies tokens locally.
- \`apps/api-auth\` — sole minter; mounts \`/auth/*\`; wraps \`@starter/auth\`.

\`@starter/api-client\` exports two typed clients: \`createApiClient\`
(for \`apps/api\`) and \`createApiAuthClient\` (for \`apps/api-auth\`).
The vite dev proxy routes \`/api/auth/*\` to the auth service and
\`/api/*\` to the main api — the browser sees one \`/api\` endpoint.
${mobileDescription}

## Diagram

\`\`\`mermaid
graph LR
    subgraph "apps/web (Vite + TanStack)"
        W["web pages<br/>(TanStack Query/Router)"]
        AC["@starter/api-client<br/>createApiClient + createApiAuthClient"]
    end

    subgraph "apps/api (Hono on Node :3000)"
        A1["AppType<br/>(items + health)"]
        M1["internal/items"]
        R1["Hono app<br/>.route('/items')"]
    end

    subgraph "apps/api-auth (Hono on Node :3001)"
        A2["AppType<br/>(/auth/*)"]
        M2["internal/auth<br/>(sole minter)"]
        R2["Hono app<br/>.route('/auth')"]
    end

    subgraph "packages/"
        DB["@starter/db<br/>(Drizzle schema)"]
        AUTH["@starter/auth<br/>(argon2 + jose — shared seam)"]
    end
${mobileDiagramMicroservices}

    W -->|typed call| AC
    AC -->|/api/*| R1
    AC -->|/api/auth/*| R2
    R1 -->|mounts| M1
    R2 -->|mounts| M2
    A1 <-->|type inference| AC
    A2 <-->|type inference| AC
    M1 -->|verifyToken| AUTH
    M2 -->|sign + verify| AUTH
    M1 -->|uses| DB
    M2 -->|uses| DB
\`\`\`

**Sole-minter invariant** (decision 11): only \`apps/api-auth\` calls
\`signToken\` / \`issueTokenPair\`. \`apps/api\` calls only
\`verifyToken()\` from the same \`@starter/auth\` package — no network
hop for verification. The shared package is the seam; the services are
deployable wrappers around it (decision 10: wrap, not replace).
`;
  }
  return `# Your Hono RPC contract spine

This is your contract spine: the single API agreement between \`apps/web\`
and \`apps/api\` in this TS-monolith scaffold (decisions 3, 9, 17, 18).

## How it works

In TS-only shapes (this one), the contract is **implicit** — shared TS
types, no artifact. The api framework is **Hono** (decision 18), so the
contract mechanism is **Hono RPC** (\`hc<typeof app>()\`): the router's TS
type *is* the wire contract, inferred end-to-end (inputs, outputs, error
shapes), no codegen, no separate source of truth to drift.

\`@starter/api-client\` imports \`AppType\` from \`@starter/api\` and builds
a typed client via \`hc<typeof app>()\`. A type error in the api is a
compile error in the web client — the contract is checked at compile time
(decision 22: type-inference *is* the contract test in TS shapes).
${mobileDescription}

## Diagram

\`\`\`mermaid
graph LR
    subgraph "apps/web (Vite + TanStack)"
        W["web pages<br/>(TanStack Query/Router)"]
        AC["@starter/api-client<br/>hc&lt;typeof app&gt;()"]
    end

    subgraph "apps/api (Hono on Node)"
        A["AppType<br/>(the router type)"]
        M["internal/auth<br/>internal/items"]
        R["Hono app<br/>.route('/auth')<br/>.route('/items')"]
    end

    subgraph "packages/"
        DB["@starter/db<br/>(Drizzle schema)"]
        AUTH["@starter/auth<br/>(argon2 + jose)"]
    end
${mobileDiagramMonolith}

    W -->|typed call| AC
    AC -->|HTTP + Bearer| R
    R -->|mounts| M
    A <-->|type inference| AC
    M -->|uses| AUTH
    M -->|uses| DB
\`\`\`

**Your Hono RPC contract spine**: the router's TS type is the contract.
The web client is generated from it by \`hc<typeof app>()\` — no artifact,
no codegen, no separate source of truth.
`;
}

function contractSpineGoMd(isMobileOn = false, mobileVariant: 'expo' | 'flutter' = 'expo'): string {
  const mobileNote = isMobileOn
    ? mobileVariant === 'flutter'
      ? '\n\nThe Flutter peer app in apps/mobile consumes the **codegen\'d Dart client** (clients/dart/ — the mobile shares *only* the contract, decision 4): it calls the api directly, stores auth tokens through flutter_secure_storage, and never imports a TS package.'
      : ''
    : '';
  return `# Your OpenAPI contract spine

This is your contract spine: the single API agreement between \`apps/web\`
and \`apps/api\` in this Go-monolith scaffold (decisions 3, 9, 19).

## How it works

In polyglot shapes (this one), the contract is **explicit** — an
\`openapi.yaml\` file in \`packages/contract\`. The api framework is
**Gin + Huma** (decision 19): operations are defined as typed Go
input/output structs on Gin routes; Huma validates at runtime and
**generates the OpenAPI spec from those structs**.

The OpenAPI file is **generated from the Go api's structs** during build
and **committed** to the repo — not hand-authored. TS/Dart clients are
then generated from the committed file.${mobileNote}

## Diagram

\`\`\`mermaid
graph LR
    subgraph "apps/web (Next.js)"
        W["web pages<br/>(RSC + loaders)"]
        C["@starter/contract<br/>(generated TS client)"]
    end

    subgraph "packages/contract"
        O["openapi.yaml<br/>(generated from Go structs)"]
    end

    subgraph "apps/api (Gin + Huma)"
        G["Gin routes<br/>(typed Go structs)"]
        H["Huma<br/>(validation + OpenAPI gen)"]
    end

    subgraph "packages/"
        DB["database<br/>(Go-native)"]
    end

    W -->|typed call| C
    C -->|HTTP| G
    G -->|validates| H
    H -->|generates| O
    G -->|uses| DB
\`\`\`

**Your OpenAPI contract spine**: Go structs are the source of truth;
the OpenAPI file is generated and committed; TS clients are generated
from it.
`;
}

function modularMonolithMd(isMicroservices: boolean): string {
  if (isMicroservices) {
    return `# The example split (TS-microservices)

This scaffold is a **TS-microservices** shape (decision 10): the
example split has already happened. \`apps/api-auth\` is a separate
deployable that owns the \`/auth/*\` HTTP surface and the signing
key. \`apps/api\` is the main API — it owns the business domains
(items here) and verifies tokens locally via the shared
\`@starter/auth\` package (no network hop).

## The split axis: capability, not domain

The example split extracts a **capability** (auth/IAM), not a business
domain. Every project has auth; not every project has "users" as a
domain (decision 10). Capability splits are real and domain-neutral
— the user carves their own domain splits by copying the example.

The split follows the **wrap, not replace** pattern (decision 10):
\`apps/api-auth\` wraps \`@starter/auth\` (it doesn't replace it).
The package remains shared across both services. The only thing
that moved is the HTTP surface + the signing key.

## How it works

\`apps/api/src/internal/<name>/\` still contains one module per
domain (items here). \`apps/api-auth/src/internal/auth/\` contains
the auth module (the same code that lived in \`apps/api\`'s
\`internal/auth/\` in the monolith shape, just relocated as its own
deployable).

\`apps/api/src/index.ts\` mounts items behind a \`requireAuth\`
middleware that uses the shared \`@starter/auth\` package:

\`\`\`ts
app
  .get('/health', (c) => c.json({ status: 'ok' }))
  .route('/items',
    new Hono().use('*', requireAuth(authConfig)).route('/', makeItemsModule()))
\`\`\`

\`apps/api-auth/src/index.ts\` mounts the auth routes:

\`\`\`ts
app
  .get('/health', (c) => c.json({ status: 'ok' }))
  .route('/auth', makeAuthModule(authConfig))
\`\`\`

## Diagram

\`\`\`mermaid
graph LR
    subgraph "apps/api (verifier)"
        I1["src/index.ts"]
        ITEMS["internal/items/"]
        MW["src/middleware/auth.ts<br/>(requireAuth → verifyToken)"]
    end

    subgraph "apps/api-auth (sole minter)"
        I2["src/index.ts"]
        AUTH["internal/auth/<br/>repo.ts + routes.ts"]
    end

    subgraph "packages/"
        DB["@starter/db"]
        AUTH_PKG["@starter/auth<br/>(shared seam)"]
    end

    I1 -->|route('/items')| ITEMS
    I1 -->|use('*', requireAuth)| MW
    MW -->|verifyToken| AUTH_PKG
    I2 -->|route('/auth')| AUTH
    AUTH -->|issueTokenPair / rotateTokenPair| AUTH_PKG
    ITEMS -->|imports| DB
    AUTH -->|imports| DB
\`\`\`

**Sole-minter invariant** (decision 11): only \`apps/api-auth\` calls
\`signToken\` / \`issueTokenPair\`. \`apps/api\` calls only
\`verifyToken()\` from the same package. The JWT_SECRET is set in
both services (HS256 is symmetric), but only one process ever
*signs*.

**Monolith → microservices** (decision 10, 27): copy this example.
Extract any \`internal/<cap>/\` module into a sibling
\`apps/api-<cap>\` service. The modular monolith's internal-module
structure is already prepared for this — the upgrade is a
seam-preserving extraction, not a refactor.
`;
  }
  return `# The modular monolith

This scaffold is a **modular monolith** (decision 27): \`apps/api\` has the
same internal-module structure as the microservices split-seam (decision
10), just without the example split having happened yet.

## How it works

\`apps/api/src/internal/<name>/\` contains one module per domain:

- \`<name>.repo.ts\` — the typed interface (the seam)
- \`<name>.routes.ts\` — the Hono router factory
- \`index.ts\` — mounts the module at a prefix

The api's \`src/index.ts\` mounts each module:

\`\`\`ts
app
  .route('/auth', makeAuthModule(...))
  .use('*', requireAuth(...))
  .route('/items', makeItemsModule(...))
\`\`\`

The **only** difference from a microservices shape is that the example
split (decision 10) hasn't happened — auth is still an \`internal/auth\`
module, not a separate \`apps/api-auth\` deployable. The monolith→microservices
upgrade is a **seam-preserving extraction**: copy the example split, no
refactor of \`apps/api\` required.

## Diagram

\`\`\`mermaid
graph LR
    subgraph "apps/api (monolith)"
        I["src/index.ts<br/>(router mounts)"]
        AUTH["internal/auth/<br/>repo.ts + routes.ts + index.ts"]
        ITEMS["internal/items/<br/>repo.ts + routes.ts + index.ts"]
    end

    subgraph "packages/"
        DB["@starter/db<br/>(Drizzle)"]
        AUTH_PKG["@starter/auth<br/>(argon2 + jose)"]
    end

    I -->|route('/auth')| AUTH
    I -->|route('/items')<br/>+ requireAuth| ITEMS
    AUTH -->|imports| AUTH_PKG
    AUTH -->|imports| DB
    ITEMS -->|imports| DB
\`\`\`

**The split-seam is present whether or not a split has happened yet**
(decision 10). The example split (extracting \`internal/auth\` →
\`apps/api-auth\`) is a future ticket; the structure is already here.
`;
}

function authSubtreeMd(isMicroservices: boolean, isMobileOn = false, mobileVariant: 'expo' | 'flutter' = 'expo'): string {
  const storage = mobileVariant === 'flutter' ? 'flutter_secure_storage' : 'expo-secure-store';
  const appLabel = mobileVariant === 'flutter' ? 'Flutter' : 'Expo';
  const mobileSection = isMobileOn
    ? `\n\n## Mobile-auth flow (decision 23)\n\nThe ${appLabel} peer app uses platform-native secure storage rather than cookies. Login and register return both tokens in the response body; apps/mobile stores them in ${storage}, attaches the access token as a Bearer header, and sends the refresh token in the body of POST /auth/refresh after a 401. The rotated pair replaces both secure-storage entries before the original request is retried.\n`
    : '';
  if (isMicroservices) {
    return `# The auth subtree (TS-microservices)

This scaffold ships an **auth shim** (decision 12): a thin typed layer
over vetted libraries that owns the surface of auth (token shape,
argon2id params, the four HTTP endpoints, refresh rotation) — not the
crypto. In **shape 2** (TS-microservices) the auth surface is served by
a dedicated sibling service: \`apps/api-auth\`.

## How it works

\`apps/api-auth\` is the **sole minter** of JWTs in this monorepo
(decision 11): only this service calls \`signToken\` /
\`issueTokenPair\`. \`apps/api\` (the main API) calls only
\`verifyToken()\` from the same shared \`@starter/auth\` package — no
network hop for verification (decision 10: wrap, not replace — the
package is the seam, the services are deployable wrappers).

Both services import the same \`@starter/auth\` package and both set
\`JWT_SECRET\` (HS256 is symmetric — verification needs the same key
as signing). The invariant is about who *signs*, not who holds the
key. The web-auth flow (decision 16) is uniform:

1. \`POST /auth/login\` (or \`/register\`) on \`apps/api-auth\` verifies
   the password via \`@starter/auth\` (argon2id), issues a token pair,
   and sets an **httpOnly refresh cookie** + returns a short-lived
   **access token** in the body.
2. \`apps/web\` stores the access token **in memory** (SPA storage model).
3. \`@starter/api-client\` attaches the access token as a **Bearer
   header** to every api call (via the vite proxy, the same \`/api\`
   base URL routes to both services).
4. On 401, the api-client calls \`POST /auth/refresh\` on the auth
   service (the httpOnly cookie is sent automatically), rotates the
   refresh token, and retries the original request.
${mobileSection}

## Diagram

\`\`\`mermaid
sequenceDiagram
    participant Browser as apps/web (SPA)
    participant Client as @starter/api-client
    participant Auth as apps/api-auth<br/>(:3001, sole minter)
    participant API as apps/api<br/>(:3000, verifier)
    participant Shim as packages/auth<br/>(shared seam)

    Note over Browser,API: Login

    Browser->>Auth: POST /api/auth/login {email, password}
    Auth->>Shim: verifyPassword (argon2id)
    Shim-->>Auth: ok
    Auth->>Shim: issueTokenPair (jose)
    Shim-->>Auth: {access, refresh}
    Auth-->>Browser: {access, refresh, userId}<br/>Set-Cookie: refresh (httpOnly)
    Note right of Browser: access token stored in memory

    Note over Browser,API: API call (Bearer)

    Browser->>Client: apiClient.items.$get()
    Client->>Browser: read in-memory access token
    Client->>API: GET /api/items<br/>Authorization: Bearer <access>
    API->>Shim: verifyToken (jose)
    Shim-->>API: ok
    API-->>Client: items list

    Note over Browser,API: Refresh on 401

    Client->>API: GET /api/items -> 401 (access expired)
    Client->>Auth: POST /api/auth/refresh<br/>(httpOnly cookie sent automatically)
    Auth->>Shim: rotateTokenPair
    Shim-->>Auth: {access, refresh}
    Auth-->>Client: {access, refresh}<br/>Set-Cookie: refresh (httpOnly)
    Client->>API: GET /api/items (retry)<br/>Authorization: Bearer <new access>
    API-->>Client: items list
\`\`\`

**Sole minter invariant** (decision 11): only \`apps/api-auth\` calls
\`signToken\` / \`issueTokenPair\`. \`apps/api\` calls only
\`verifyToken()\` from the same package — local, no network hop. The
httpOnly cookie protects the refresh token from XSS; the short-lived
access token is briefly readable during its lifetime — the standard,
accepted JWT tradeoff.
`;
  }
  return `# The auth subtree

This scaffold ships an **auth shim** (decision 12): a thin typed layer over
vetted libraries that owns the surface of auth (token shape, argon2id
params, the four HTTP endpoints, refresh rotation) — not the crypto.

## How it works

\`apps/api\` is the **sole minter** of JWTs in this monorepo (decision 11):
no other service reads \`JWT_SECRET\`. The web-auth flow (decision 16) is
uniform across web variants:

1. \`POST /auth/login\` (or \`/register\`) verifies the password via
   \`packages/auth\` (argon2id), issues a token pair, and sets an **httpOnly
   refresh cookie** + returns a short-lived **access token** in the body.
2. \`apps/web\` stores the access token **in memory** (SPA storage model).
3. \`@starter/api-client\` attaches the access token as a **Bearer header**
   to every api call.
4. On 401, \`api-client\` calls \`POST /auth/refresh\` (which re-reads the
   httpOnly cookie), rotates the refresh token, and retries the original
   request.
${mobileSection}

## Diagram

\`\`\`mermaid
sequenceDiagram
    participant Browser as apps/web (SPA)
    participant Client as @starter/api-client
    participant API as apps/api
    participant Auth as packages/auth

    Note over Browser,API: Login

    Browser->>API: POST /auth/login {email, password}
    API->>Auth: verifyPassword (argon2id)
    Auth-->>API: ok
    API->>Auth: issueTokenPair (jose)
    Auth-->>API: {access, refresh}
    API-->>Browser: {access, refresh, userId}<br/>Set-Cookie: refresh (httpOnly)
    Note right of Browser: access token stored in memory

    Note over Browser,API: API call (Bearer)

    Browser->>Client: apiClient.items.$get()
    Client->>Browser: read in-memory access token
    Client->>API: GET /items<br/>Authorization: Bearer <access>
    API->>Auth: verifyToken (jose)
    Auth-->>API: ok
    API-->>Client: items list

    Note over Browser,API: Refresh on 401

    Client->>API: GET /items -> 401 (access expired)
    Client->>API: POST /auth/refresh<br/>(httpOnly cookie sent automatically)
    API->>Auth: rotateTokenPair
    Auth-->>API: {access, refresh}
    API-->>Client: {access, refresh}<br/>Set-Cookie: refresh (httpOnly)
    Client->>API: GET /items (retry)<br/>Authorization: Bearer <new access>
    API-->>Client: items list
\`\`\`

**Sole minter invariant** (decision 11): only \`apps/api\` holds the private
signing key. The httpOnly cookie protects the refresh token from XSS; the
short-lived access token is briefly readable during its lifetime — the
standard, accepted JWT tradeoff.
`;
}

function mobileAuthFlowMd(isMicroservices: boolean, mobileVariant: 'expo' | 'flutter' = 'expo'): string {
  const authService = isMicroservices ? 'apps/api-auth' : 'apps/api';
  const appLabel = mobileVariant === 'flutter' ? 'Flutter' : 'Expo';
  const storage = mobileVariant === 'flutter' ? 'flutter_secure_storage' : 'expo-secure-store';
  const envVars = mobileVariant === 'flutter'
    ? (isMicroservices
        ? 'API_URL / AUTH_URL (--dart-define, defaults http://localhost:3000 / http://localhost:3001)'
        : 'API_URL (--dart-define, defaults to http://localhost:3000)')
    : (isMicroservices ? 'EXPO_PUBLIC_API_URL + EXPO_PUBLIC_AUTH_URL' : 'EXPO_PUBLIC_API_URL');
  const client = mobileVariant === 'flutter'
    ? 'the codegen\'d Dart client (packages/contract/clients/dart)'
    : 'the same typed Hono RPC client as apps/web';
  return `# Mobile auth flow (${appLabel})

The mobile app is a peer client, not a web shell with cookies bolted on.
It uses ${client}, but its token storage
and refresh transport follow decision 23:

1. POST /auth/login returns both access and refresh tokens in the body.
2. apps/mobile stores both values in ${storage}.
3. Every protected request carries Authorization: Bearer <access>.
4. A 401 reads the refresh token from secure storage and POSTs it to
   /auth/refresh in a JSON body, never in a cookie.
5. The rotated pair replaces both secure-storage values and the original
   request is retried once.

The auth base URL is configured via ${envVars}. In this shape, ${authService} owns the
four auth endpoints and is the sole token minter. The items API remains the
other base URL in the microservices shape.

## Sequence

\`\`\`mermaid
sequenceDiagram
    participant Mobile as apps/mobile (${appLabel})
    participant Store as ${storage}
    participant Auth as ${authService}
    participant API as apps/api

    Mobile->>Auth: POST /auth/login {email, password}
    Auth-->>Mobile: {access, refresh}
    Mobile->>Store: save access + refresh
    Mobile->>API: GET /items<br/>Authorization: Bearer access
    API-->>Mobile: 401 (access expired)
    Mobile->>Store: read refresh
    Mobile->>Auth: POST /auth/refresh {refresh}
    Auth-->>Mobile: {access, refresh}
    Mobile->>Store: replace both tokens
    Mobile->>API: retry GET /items<br/>Authorization: Bearer access
    API-->>Mobile: items
\`\`\`

Native builds and a device/emulator need a host address reachable from the
runtime. Use http://10.0.2.2:3000 from the Android emulator, localhost from
the iOS simulator, or the development machine's LAN IP from a physical
device.
`;
}

function typedRpcTransportTsMd(isMicroservices: boolean): string {
  if (isMicroservices) {
    return `# The typed-RPC transport (TS-microservices)

The web reaches the backends through \`@starter/api-client\`, which
exports **two** typed Hono RPC clients (decision 15/17/10):

- \`createApiClient\` — typed against \`apps/api\`'s \`AppType\` (items + health)
- \`createApiAuthClient\` — typed against \`apps/api-auth\`'s \`AppType\` (auth/*)

Both are built from the router's TS type via \`hc<typeof app>()\`.
The transport rule (decision 17b) is:

> **Batch by default; unbatch only where batching would defeat server-side
> fetch memoization.**

In this TS scaffold (Vite + TanStack, no server-side rendering), there
is no server-side \`fetch\` patching context, so the client is
**fully batched** — Hono RPC's HTTP transport.

## How it works

The vite dev proxy routes \`/api/auth/*\` to \`apps/api-auth\` (port 3001)
and \`/api/*\` to \`apps/api\` (port 3000). Both clients use the same
\`/api\` base URL; the proxy handles the routing. The httpOnly refresh
cookie stays first-party (same origin) in both dev and production.

\`@starter/api-client\` wraps \`hono/client\`'s \`hc<typeof app>()\` with
typed factory functions. The auth wiring (apps/web/src/lib/api.ts):

1. Reads the in-memory access token from the auth context.
2. Attaches it as a \`Bearer\` header on every non-auth request.
3. On 401, calls \`POST /auth/refresh\` via the auth client (which
   reads the httpOnly cookie), updates the in-memory token, and
   retries the original request.
4. Excludes the \`/auth/*\` routes from refresh-on-401 (the auth
   surface is the refresh mechanism itself — recursing would loop).

## Diagram

\`\`\`mermaid
graph TD
    subgraph "apps/web"
        TQ["TanStack Query<br/>useQuery / useMutation"]
        AC["@starter/api-client<br/>createApiClient + createApiAuthClient"]
        AUTH["useAuth<br/>(in-memory access token)"]
    end

    subgraph "Transport"
        BEARER["Bearer header<br/>(access token)"]
        REFRESH["Refresh-on-401<br/>POST /auth/refresh<br/>(httpOnly cookie)"]
    end

    subgraph "Vite proxy"
        PROXY["/api/auth/* → :3001<br/>/api/* → :3000"]
    end

    subgraph "apps/api-auth (:3001)"
        AUTH_SVC["Hono app<br/>.route('/auth')"]
    end

    subgraph "apps/api (:3000)"
        API_SVC["Hono app<br/>.route('/items')"]
    end

    TQ -->|typed call| AC
    AC -->|attach token| BEARER
    AC -->|401 -> refresh -> retry| REFRESH
    BEARER -->|HTTP| PROXY
    REFRESH -->|HTTP| PROXY
    PROXY -->|/api/auth/*| AUTH_SVC
    PROXY -->|/api/*| API_SVC
    AUTH -->|provides token| AC
\`\`\`

**The rule is keyed to a runtime property** (server-side \`fetch\` patching),
not a per-variant label — so it extends to future variants (TanStack Start)
by checking the same property, not by adding a new carve-out.
`;
  }
  return `# The typed-RPC transport

The web reaches the api through \`@starter/api-client\`, a typed Hono RPC
client (decision 15/17). The transport rule (decision 17b) is:

> **Batch by default; unbatch only where batching would defeat server-side
> fetch memoization.**

In this TS-monolith scaffold (Vite + TanStack, no server-side rendering),
there is no server-side \`fetch\` patching context, so the client is
**fully batched** — \`httpBatchLink\`-equivalent behavior via Hono RPC's
HTTP transport.

## How it works

\`@starter/api-client\` wraps \`hono/client\`'s \`hc<typeof app>()\` with a
typed \`createApiClient\` that:

1. Reads the in-memory access token from the auth context.
2. Attaches it as a \`Bearer\` header on every request.
3. On 401, calls \`POST /auth/refresh\` (which reads the httpOnly cookie),
   updates the in-memory token, and retries the original request.
4. Excludes the \`/auth/*\` routes from refresh-on-401 (the auth surface is
   the refresh mechanism itself — recursing would loop).

## Diagram

\`\`\`mermaid
graph TD
    subgraph "apps/web"
        TQ["TanStack Query<br/>useQuery / useMutation"]
        AC["createApiClient<br/>(api-client wrapper)"]
        AUTH["useAuth<br/>(in-memory access token)"]
    end

    subgraph "Transport"
        BATCH["Batch-by-default<br/>(httpBatchLink-equivalent)"]
        BEARER["Bearer header<br/>(access token)"]
        REFRESH["Refresh-on-401<br/>POST /auth/refresh<br/>(httpOnly cookie)"]
    end

    subgraph "apps/api"
        API["Hono app<br/>hc&lt;typeof app&gt;()"]
    end

    TQ -->|typed call| AC
    AC -->|attach token| BEARER
    AC -->|401 -> refresh -> retry| REFRESH
    AC -->|batch requests| BATCH
    BATCH -->|HTTP| API
    AUTH -->|provides token| AC
\`\`\`

**The rule is keyed to a runtime property** (server-side \`fetch\` patching),
not a per-variant label — so it extends to future variants (TanStack Start)
by checking the same property, not by adding a new carve-out.
`;
}

function typedRpcTransportGoMd(): string {
  return `# The OpenAPI transport

The web reaches the api through a generated TS client from
\`packages/contract/openapi.yaml\` (decision 19). The contract is
**explicit** — an OpenAPI spec generated from Go structs and committed.

## How it works

\`packages/contract\` holds the committed \`openapi.yaml\` and generated
clients. The web uses the generated TS client; mobile (Flutter) uses
the generated Dart client. Both are generated from the same spec.

The Go api uses **Gin + Huma** (decision 19): operations are defined as
typed Go input/output structs; Huma validates at runtime and generates
the OpenAPI spec during build.

## Diagram

\`\`\`mermaid
graph TD
    subgraph "apps/web (Next.js)"
        W["RSC / loaders"]
        C["generated TS client"]
    end

    subgraph "packages/contract"
        O["openapi.yaml<br/>(generated + committed)"]
    end

    subgraph "apps/api (Gin + Huma)"
        G["Gin routes<br/>(Go structs)"]
        H["Huma<br/>(validation + gen)"]
    end

    W -->|typed call| C
    C -->|HTTP| G
    H -->|generates| O
    C -->|generated from| O
\`\`\`

**The OpenAPI spec is the spine**: Go structs are the source of truth,
the spec is generated and committed, clients are generated from it.
`;
}

function adrReadmeMd(): string {
  return `# Architecture Decision Records (ADRs)

This directory is **empty by default** — it's a convention for recording
your scaffolded project's *own* future architecture decisions, extending
the ADR pattern this Starter uses internally in \`CONTEXT.md\`.

## The convention

An ADR is a short document that records a single architectural decision:
the context, the options considered, the decision made, and the
consequences. Each ADR lives in its own file:

\`\`\`
docs/adr/
  0001-record-architecture-decisions.md   (template - copy this)
  0002-add-a-new-web-variant.md
  0003-monolith-to-microservices-split.md
\`\`\`

### File naming

\`<NNNN>-<kebab-case-title>.md\` — a zero-padded number (sequential),
followed by a short, descriptive title. The number is the ADR's identity;
the title is for humans.

### Template

Every ADR follows the same structure (adapted from Michael Nygard's
[Documenting Architecture Decisions](https://adr.github.io/)):

\`\`\`markdown
# NNNN. <Title>

Date: YYYY-MM-DD
Status: proposed | accepted | superseded by [ADR NNNN] | deprecated

## Context

What is the issue we're facing? What are the forces at play?

## Decision

What is the change that we're proposing and have agreed to?

## Consequences

What becomes easier or more difficult to do because of this change?
\`\`\`

## When to write an ADR

Write one when you make a decision that:

- Changes the project's structure (e.g. adding a new workspace, splitting
  a module into a service per decision 10's pattern).
- Changes the contract (e.g. adding an operation, switching the
  contract mechanism).
- Changes the deployment topology (e.g. monolith to microservices).
- Adds a new fence from the auth shim (e.g. OAuth, MFA — decision 12).
- Adds a new web variant (e.g. Next to Vite swap — decision 15).

You don't need an ADR for: adding a route, adding a column, fixing a
bug. The bar is "this decision shapes the architecture."

## Relationship to CONTEXT.md

This Starter's \`CONTEXT.md\` is the predecessor to this ADR convention —
it records the decisions that produced *this scaffold*. As you grow your
project, your ADRs in this directory record the decisions that produce
*your* architecture. The recursion is intentional: a contributor who
learns the ADR pattern from this scaffolded project can apply it to any
project.
`;
}

function codeStyleTsMd(): string {
  return `# Code style

This project uses **Biome** for TypeScript (decision 29): a single tool
for linting and formatting, replacing ESLint + Prettier. The one-tool
discipline (parallels decision 8's "one orchestrator") refuses two tools
when one does the job.

## Biome (TypeScript)

- **Config**: \`biome.json\` at the project root. The config is the
  *truth*; this doc is the *justification*.
- **Lint + format**: \`biome check\` lints, \`biome format\` formats.
  Run \`pnpm lint\` and \`pnpm format\` (wired in each workspace's
  \`package.json\`).
- **Why Biome**: zero-config defaults, fast, native, replaces
  ESLint + Prettier (two tools for one job). The one-tool discipline
  means there's no ESLint config to drift from the Prettier config.
- **Pre-commit**: the scaffolded project ships a \`lint-staged\`-equivalent
  via Biome's own git hooks integration. Run \`biome ci\` in CI to fail
  on unformatted or unlinted code.

## What this doesn't cover

- **Go**: gofmt + golangci-lint (consensus, no real fork). Not present
  in this TS-monolith scaffold — Go appears in polyglot shapes (3, 4).
- **Python**: ruff + \`ruff format\` (shape 4 AI service). Not present
  in this scaffold — Python appears only in Go-microservices with AI.
`;
}

function codeStyleGoMd(): string {
  return `# Code style

This project uses **gofmt + golangci-lint** for Go (decision 29):
the consensus Go toolchain, no real fork.

## Go formatting and linting

- **gofmt**: formats Go code canonically. Run \`gofmt -w .\` or use your
  editor's auto-format.
- **golangci-lint**: meta-linter that runs dozens of Go linters in parallel.
  Config in \`.golangci.yml\`. Run \`golangci-lint run\` or \`task lint\`.
- **Why this pair**: gofmt is the canonical Go formatter (no config needed);
  golangci-lint is the community consensus meta-linter. One formatter +
  one meta-linter = the one-tool discipline applied to Go.

## What this doesn't cover

- **TypeScript**: Biome (see the TS-monolith scaffold's code-style doc).
- **Python**: ruff + \`ruff format\` (shape 4 AI service). Not present
  in this scaffold — Python appears only in Go-microservices with AI.
`;
}

function bestPracticesMd(isMicroservices: boolean): string {
  if (isMicroservices) {
    return `# Best practices (per seam) — TS-microservices

Action-oriented guides for the things scaffolded-project users actually
do in the **TS-microservices** shape. Each seam is one line + a link
into the detail.

## Add a module to the main api (decision 27)

The scaffolded \`apps/api\` is a modular monolith with the example split
already done. Each domain lives in \`apps/api/src/internal/<name>/\` with
a typed interface, a Hono router, and a mountable index.

1. Create \`apps/api/src/internal/<name>/\`.
2. Write \`<name>.repo.ts\` — the typed interface (the seam):

\`\`\`ts
export interface ItemsRepo {
  list(): Promise<Item[]>;
  create(input: { name: string }): Promise<Item>;
}
\`\`\`

3. Write \`<name>.routes.ts\` — the Hono router factory.
4. Write \`<name>.repo.drizzle.ts\` — the Drizzle-backed implementation.
5. Mount it in \`apps/api/src/index.ts\`:

\`\`\`ts
app.route('/items',
  new Hono().use('*', requireAuth(authConfig)).route('/', makeItemsModule()));
\`\`\`

Behind \`requireAuth\` if it needs an authenticated principal.

## Extend the contract (decisions 3, 17, 18)

There are **two** typed surfaces in this shape:

- \`apps/api\`'s \`AppType\` — items + health. Consumed by
  \`createApiClient\` in \`@starter/api-client\`.
- \`apps/api-auth\`'s \`AppType\` — /auth/*. Consumed by
  \`createApiAuthClient\` in \`@starter/api-client\`.

To add an operation:

1. Add a route to the relevant service's Hono router.
2. The web client picks it up automatically — \`hc<typeof app>()\`
   infers the new operation. No codegen, no artifact.
3. Run \`pnpm typecheck\` in \`apps/web\` to verify the typed client
   matches (a type error *is* a contract test, decision 22).

## Add a db table (decision 14)

1. Add a schema to \`packages/db/src/schema/<name>.ts\`.
2. Re-export it from \`packages/db/src/index.ts\`.
3. Run \`task db:generate\` to emit a migration.
4. Run \`task migrate\` to apply it.

## Wire a fence from the auth shim (decision 12)

See \`docs/wire-it-in/auth.md\` for the seams (email-verify, password
reset, MFA, OAuth, RBAC). Each fence is a documented handoff: the shim
owns the surface, you own the implementation. The fence lands in
\`apps/api-auth/src/internal/auth/\` (the sole minter).

## Add a web page (decision 15)

1. Create a route in \`apps/web/src/pages/<name>.tsx\`.
2. Register it in \`apps/web/src/router.tsx\`.
3. Reach the api through \`apiClient\` (items) or \`apiAuthClient\`
   (auth) — both re-exported from \`apps/web/src/lib/api\`. No direct
   fetch, no DB access from the web (decision 15: the api-client is
   the only door).

## Split another capability out of apps/api (decisions 10, 27)

The example split (extracting auth → apps/api-auth) is the pattern.
To extract another capability:

1. Create \`apps/api/src/internal/<cap>/\` in apps/api (interface +
   routes + drizzle impl).
2. When it's ready to split, copy the module into a new sibling
   service: \`apps/api-<cap>/\`. Wrap the shared package (if any).
3. Mount it in \`apps/api-<cap>/src/index.ts\`.
4. Update the vite proxy in \`apps/web/vite.config.ts\` to route
   \`/api/<cap>/*\` to the new service.
5. Update \`@starter/api-client\` to export a typed client for the
   new service.

The modular monolith's \`internal/*\` structure is already prepared
for this — the upgrade is a seam-preserving extraction, not a refactor.
`;
  }
  return `# Best practices (per seam)

Action-oriented guides for the things scaffolded-project users actually
do. Each seam is one line + a link into the detail.

## Add a module to the modular monolith (decision 27)

The scaffolded \`apps/api\` is a modular monolith: each domain lives in
\`apps/api/src/internal/<name>/\` with a typed interface, a Hono router,
and a mountable index.

1. Create \`apps/api/src/internal/<name>/\`.
2. Write \`<name>.repo.ts\` — the typed interface (the seam):

\`\`\`ts
export interface ItemsRepo {
  list(): Promise<Item[]>;
  create(input: { name: string }): Promise<Item>;
}
\`\`\`

3. Write \`<name>.routes.ts\` — the Hono router factory:

\`\`\`ts
export function makeItemsRoutes(repo: ItemsRepo): Hono {
  return new Hono()
    .get('/', ...)
    .post('/', ...);
}
\`\`\`

4. Write \`<name>.repo.drizzle.ts\` — the Drizzle-backed implementation.
5. Mount it in \`apps/api/src/index.ts\`:

\`\`\`ts
app.route('/items', makeItemsModule(deps));
\`\`\`

Behind \`requireAuth\` if it needs an authenticated principal.

## Extend the contract (decisions 3, 17, 18)

The contract is the Hono router's TS type. To add an operation:

1. Add a route to the relevant module's Hono router.
2. The web client picks it up automatically — \`hc<typeof app>()\`
   infers the new operation. No codegen, no artifact.
3. Run \`pnpm typecheck\` in \`apps/web\` to verify the typed client
   matches (a type error *is* a contract test, decision 22).

## Add a db table (decision 14)

1. Add a schema to \`packages/db/src/schema/<name>.ts\`.
2. Re-export it from \`packages/db/src/index.ts\`.
3. Run \`task db:generate\` to emit a migration.
4. Run \`task migrate\` to apply it.

## Wire a fence from the auth shim (decision 12)

See \`docs/wire-it-in/auth.md\` for the seams (email-verify, password
reset, MFA, OAuth, RBAC). Each fence is a documented handoff: the shim
owns the surface, you own the implementation.

## Add a web page (decision 15)

1. Create a route in \`apps/web/src/pages/<name>.tsx\`.
2. Register it in \`apps/web/src/router.tsx\`.
3. Reach the api through \`apiClient\` (re-exported from
   \`apps/web/src/lib/api\`) — no direct fetch, no DB access from the
   web (decision 15: the api-client is the only door).

## Monolith to microservices (decisions 10, 27)

The example split (extracting \`internal/auth\` to \`apps/api-auth\`) is a
future ticket. When it lands, the pattern is: copy the example, don't
refactor. The modular monolith's \`internal/*\` structure is already
prepared to receive the extraction.
`;
}

function antiPatternsMd(): string {
  return `# Anti-patterns

A "don't do this" list drawn from the **rejected options** recorded in
every decision in \`CONTEXT.md\`. Each anti-pattern is paired with the
decision that killed it. This is the unique asset: 30+ decisions of
"we considered X, rejected because Y" captured in one searchable doc.

A code reviewer asked "why isn't this using X?" can now point here
instead of reading \`CONTEXT.md\` cover-to-cover.

---

## Decision 1 — Form of the Starter

**Anti-pattern: Kitchen-sink clone.**
A static template or a pre-built fullstack app that the user forks.
Rejected: it doesn't scale to variants (mobile yes/no, web variant,
backend language) and becomes a maintenance burden. The starter is a
CLI scaffolder (decision 1) that generates projects from prompts, not a
clone to fork.

## Decision 10 — Microservices scaffolding

**Anti-pattern: Premature N-service decomposition.**
Splitting \`apps/api\` into many services at scaffold time, before the
user has any business domains to split. Rejected: the user's own later
splits follow the example, not a premature decomposition.

**Anti-pattern: Monolith + README bait-and-switch.**
Shipping a monolith with a README that says "imagine this split into
services." Rejected: the seam must be real (proven by the example split),
not aspirational.

**Anti-pattern: Capability split on a business domain.**
Extracting \`apps/api-users\` as the example split. Rejected: every
project has auth (a cross-cutting capability), not every project has
users. The example must be domain-neutral.

## Decision 12 — Auth implementation depth

**Anti-pattern: Genuinely real minimal auth (Option A).**
Shipping a from-scratch auth implementation that's "real." Rejected:
real auth has no minimum, and shipping it makes the starter a maintained
auth framework (every CVE, every rotation bug lands forever).

**Anti-pattern: Documented stub (Option C).**
A real seam wrapping a fake capability. Rejected: the same bait-and-switch
as the monolith + README — a real seam with a fake capability is theater.

**Anti-pattern: OAuth/PKCE in the starter.**
Shipping OAuth/PKCE as a built-in auth flow. Rejected: it broadens the
shim's scope beyond the four endpoints; OAuth is a fenced "wire it in"
item, not a scaffolded feature.

## Decision 14 — DB layer

**Anti-pattern: Raw \`pg\` driver + standalone migration runner.**
Leaving the data layer untyped. Rejected per decision 14: it undercuts the
typed-TS-spine reason the implicit-contract path exists (decision 3).

**Anti-pattern: Prisma.**
Non-TS schema language and a generated per-app client fight the
shared-real-workspace model (decision 9); heaviest runtime of the three.
Rejected per decision 14.

**Anti-pattern: Dual source of truth (SQL migration + Drizzle TS schema).**
Hand-authored SQL migrations alongside a Drizzle schema. Rejected per
decision 14: the real swap-point is the repo layer in \`apps/api\`, not
the migration history.

## Decision 17 — Implicit-contract mechanism

**Anti-pattern: Codegen from route types.**
Reintroducing an artifact (a build step per api change). Rejected per
decision 17: decision 3 said the implicit contract *isn't* an artifact.

**Anti-pattern: Zod + hand-rolled fetch.**
Splits the source of truth (schemas vs route behavior); bespoke fetch
plumbing the starter owns forever. Rejected per decision 17.

**Anti-pattern: Bolting tRPC onto Hono.**
Redundant: Hono already provides typed RPC (\`hc<typeof app>()\`), so
tRPC would be a competing runtime bolted on. Rejected per decision 18
(decision 17 cascade).

## Decision 18 — API framework (TS shapes)

**Anti-pattern: API framework as a variant.**
Making Hono vs Fastify a scaffold-time choice. Rejected: it doubles
shape 2's CI surface and couples the contract-mechanism axis
(tRPC vs Hono RPC) to the framework choice.

**Anti-pattern: Express.**
Audience-safe but older/slower, no native typed RPC, no OpenAPI continuity.

**Anti-pattern: Elysia.**
Bun-only, runtime-locked — directly fights decision 10's swappable-api
thesis.

## Decision 19 — Go API framework (polyglot shapes)

**Anti-pattern: Authored-as-source OpenAPI.**
Keeping OpenAPI hand-authored as the symmetric source of truth.
Rejected per decision 19: gives up the structs-as-source workflow
(Huma+Gin) the user actually used and liked.

**Anti-pattern: Introspection (\`GET /verify\` per request).**
Per-request token verification against a central auth service.
Rejected per decision 19: opposite failure mode and latency profile
from shape 2's local-verify (decision 11).

## Decision 20 — AI layer

**Anti-pattern: Single chat-completion shim (Option A).**
Ships one AI product (chat), wrong for most projects.

**Anti-pattern: RAG toolkit (Option B).**
Ships one AI product (RAG = embeddings + vector store + chat), wrong for
most projects *and* imposes "AI = RAG" as the starter's opinion.

**Anti-pattern: Typed seam only, no implementation (Option C).**
A capability wrapping an empty implementation — the same bait-and-switch
decision 12 rejected for auth.

**Anti-pattern: Disposable example composition (Option D1).**
An AI example would impose "AI is a thing this project does" on projects
that don't, since AI is opt-in unlike auth (decision 21).

## Decision 21 — AI as opt-in

**Anti-pattern: AI always scaffolded-in (original decision 5 reading).**
"Always available" as zero-friction presence means every non-AI project
carries an unused \`packages/ai\` with SDK dependencies, contradicting
the opt-in principle applied to kill the example (decision 20).

## Decision 24 — CLI composition policy

**Anti-pattern: Strict only-2x2 generatable (Option A).**
Paternalistic; refuses sensible user choices (e.g. Vite for a Go shape
if Next is the blessed Go web variant), contradicting the "swappable
peers, trust the seams" philosophy. Rejected per decision 24.

**Anti-pattern: Tiered — blessed 4 + smoke-tested adjacencies (Option C).**
Most nuanced but the hardest to maintain: defining "sensible" vs
"nonsensical" is a real ongoing investment, and the smoke-test layer
is real CI cost. Rejected per decision 24.

## Decision 26 — packages/shared scope

**Anti-pattern: Domain DTOs in \`packages/shared\` with a separate mobile client (Option B).**
Would require Expo to *not* use the Hono RPC client, but decision 23
already locked mobile to \`api-client\`. Introduces a *dual* source of
types (the inferred router + authored shared DTOs) that must agree —
drift risk. Rejected per decision 26.

## Decision 27 — Monolith structure

**Anti-pattern: Flatter monolith, routes directly on the api (Option B).**
The monolith-to-microservices upgrade becomes a *structural rewrite*
(refactor \`apps/api\` into \`internal/*\` with explicit interfaces before
the example split means anything). Contradicts decision 10's "present
whether or not a split has happened yet." Rejected per decision 27.

**Anti-pattern: Hybrid — lightweight \`internal/*\` in monolith, strict in microservices (Option C).**
Fuzzy line (which interfaces need hardening on upgrade?); two shapes
have *different* module models (loose folders vs strict-interface modules).
Rejected per decision 27.

## Decision 29 — CI / lint / format

**Anti-pattern: ESLint + Prettier (two tools for one job).**
Fights the one-tool discipline. Biome replaces both.

**Anti-pattern: Legacy Python toolchain (Black + isort + Flake8).**
Three tools where one (ruff) suffices. Replaced per decision 29.

**Anti-pattern: Web-only CI blessed matrix (Option A).**
Declaring mobile a peer (decision 2) while never testing it is the soft
bait-and-switch the starter rejects elsewhere.

## Decision 32 — Docs standards sub-docs

**Anti-pattern: Single CONVENTIONS.md in each repo's root (Option B).**
Scope (style + patterns + anti-patterns) gets unwieldy; one file doesn't
surface the recursion (decision 30's mirror works because each subdir has
a clear responsibility). Rejected per decision 32.

**Anti-pattern: Inline in the README (Option C).**
Standards/practices content is the wrong shape for a "what is this
project" entry point and gets read once and forgotten. The standards
subdir (decision 32) gives these docs their own home.
`;
}
