// Materializer: packages/contract templates for the Go-microservices
// shape 4 (issue #15).
//
// In the polyglot shapes (3 & 4) packages/contract is the ONLY shared
// package (decision 9). Go is the canonical side (decision 19) — but
// shape 4 has TWO Go services, so the committed spec is generated in
// three committed steps, all tripwired:
//
//   openapi.api.yaml   — generated by apps/api's specgen (the main
//                        api's routes: /items). Tripwire:
//                        apps/api/contract_test.go == live spec.
//   openapi.auth.yaml  — generated by apps/api-auth's specgen (the
//                        auth service's routes: /auth/* + JWKS).
//                        Tripwire: apps/api-auth/contract_test.go.
//   openapi.yaml       — the MERGED spec: what TS/Dart clients are
//                        generated from (the spine, decision 9).
//                        Generated by scripts/merge-openapi.mjs from
//                        the two partials. Tripwire:
//                        test/generated.test.ts re-runs the merge.
//
// A spec change therefore flows Go structs -> each service's specgen
// -> merge -> client generation, all via `task contract:generate`,
// and is committed as one diff — clients can only pick it up after
// that regeneration (the Go-as-canonical rule, decision 19).
//
// Per issue #27 the materializer is split by workspace; this module
// owns every file written into packages/contract for shape 4.
// Templates shared with the Go-monolith (package.json, tsconfig, the
// TS client generator, the Dart client) are imported from
// go-contract.js; only the shape-4-specific files live here.

import { join } from 'node:path';
import { type ProjectContext, writeFileRecursive } from './_shared.js';
import {
  clientTs,
  contractPackageJson,
  contractTsconfigJson,
  dartPubspec,
  generateDartClientMjs,
  generateTsClientMjs,
} from './go-contract.js';

export async function writeGoContractMs(ctx: ProjectContext): Promise<void> {
  const { targetDir } = ctx;

  await writeFileRecursive(join(targetDir, 'packages/contract/openapi.api.yaml'), openapiApiYaml());
  await writeFileRecursive(join(targetDir, 'packages/contract/openapi.auth.yaml'), openapiAuthYaml());
  await writeFileRecursive(join(targetDir, 'packages/contract/openapi.yaml'), openapiMergedYaml());
  await writeFileRecursive(join(targetDir, 'packages/contract/package.json'), contractPackageJson());
  await writeFileRecursive(join(targetDir, 'packages/contract/tsconfig.json'), contractTsconfigJson());
  await writeFileRecursive(join(targetDir, 'packages/contract/README.md'), contractReadmeMs());
  await writeFileRecursive(join(targetDir, 'packages/contract/scripts/merge-openapi.mjs'), mergeOpenapiMjs());
  await writeFileRecursive(join(targetDir, 'packages/contract/scripts/generate-ts-client.mjs'), generateTsClientMjs());
  await writeFileRecursive(join(targetDir, 'packages/contract/src/types.ts'), clientTypesTsMs());
  await writeFileRecursive(join(targetDir, 'packages/contract/src/client.ts'), clientTs());
  await writeFileRecursive(join(targetDir, 'packages/contract/src/index.ts'), clientIndexTsMs());
  await writeFileRecursive(join(targetDir, 'packages/contract/test/generated.test.ts'), generatedTestTsMs());
  await writeFileRecursive(join(targetDir, 'packages/contract/clients/dart/pubspec.yaml'), dartPubspec());
  await writeFileRecursive(join(targetDir, 'packages/contract/scripts/generate-dart-client.mjs'), generateDartClientMjs());
  await writeFileRecursive(join(targetDir, 'packages/contract/clients/dart/lib/openapi_client.dart'), dartClientMs());
}

function openapiApiYaml(): string {
  return `components:
    schemas:
        ErrorDetail:
            additionalProperties: false
            properties:
                location:
                    description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
                    type: string
                message:
                    description: Error message text
                    type: string
                value:
                    description: The value at the given location
            type: object
        ErrorModel:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/ErrorModel.json
                    format: uri
                    readOnly: true
                    type: string
                detail:
                    description: A human-readable explanation specific to this occurrence of the problem.
                    examples:
                        - Property foo is required but is missing.
                    type: string
                errors:
                    description: Optional list of individual error details
                    items:
                        $ref: '#/components/schemas/ErrorDetail'
                    type:
                        - array
                        - "null"
                instance:
                    description: A URI reference that identifies the specific occurrence of the problem.
                    examples:
                        - https://example.com/error-log/abc123
                    format: uri
                    type: string
                status:
                    description: HTTP status code
                    examples:
                        - 400
                    format: int64
                    type: integer
                title:
                    description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
                    examples:
                        - Bad Request
                    type: string
                type:
                    default: about:blank
                    description: A URI reference to human-readable documentation for the error.
                    examples:
                        - https://example.com/errors/example
                    format: uri
                    type: string
            type: object
        Item:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/Item.json
                    format: uri
                    readOnly: true
                    type: string
                created_at:
                    format: date-time
                    type: string
                id:
                    type: string
                name:
                    maxLength: 200
                    type: string
            required:
                - id
                - name
                - created_at
            type: object
        ItemCreateInputBody:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/ItemCreateInputBody.json
                    format: uri
                    readOnly: true
                    type: string
                name:
                    description: Name of the item
                    maxLength: 200
                    minLength: 1
                    type: string
            required:
                - name
            type: object
    securitySchemes:
        bearerAuth:
            bearerFormat: JWT
            description: A short-lived access token (decision 16), minted by apps/api-auth (the sole minter, decision 11); verified locally against its fetched-and-cached JWKS.
            scheme: bearer
            type: http
info:
    description: 'The scaffolded Go api: items demo behind a JWKS-verified Bearer gate (decision 13/11). Auth lives on apps/api-auth (the sole minter).'
    title: Starter API
    version: 0.1.0
openapi: 3.1.0
paths:
    /items:
        get:
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/Item'
                                type:
                                    - array
                                    - "null"
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            security:
                - bearerAuth: []
            summary: List items
            tags:
                - items
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ItemCreateInputBody'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            security:
                - bearerAuth: []
            summary: Create an item
            tags:
                - items
`;
}

function openapiAuthYaml(): string {
  return `components:
    schemas:
        AuthCredentialsInputBody:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/AuthCredentialsInputBody.json
                    format: uri
                    readOnly: true
                    type: string
                email:
                    format: email
                    maxLength: 256
                    type: string
                password:
                    maxLength: 256
                    minLength: 1
                    type: string
            required:
                - email
                - password
            type: object
        AuthRefreshInputBody:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/AuthRefreshInputBody.json
                    format: uri
                    readOnly: true
                    type: string
                refresh:
                    type: string
            type: object
        AuthRegisterInputBody:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/AuthRegisterInputBody.json
                    format: uri
                    readOnly: true
                    type: string
                email:
                    format: email
                    maxLength: 256
                    type: string
                password:
                    maxLength: 256
                    minLength: 8
                    type: string
            required:
                - email
                - password
            type: object
        AuthRegisterOutputBody:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/AuthRegisterOutputBody.json
                    format: uri
                    readOnly: true
                    type: string
                access:
                    type: string
                refresh:
                    type: string
                user:
                    $ref: '#/components/schemas/AuthUser'
            required:
                - access
                - refresh
                - user
            type: object
        AuthTokens:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/AuthTokens.json
                    format: uri
                    readOnly: true
                    type: string
                access:
                    type: string
                refresh:
                    type: string
            required:
                - access
                - refresh
            type: object
        AuthUser:
            additionalProperties: false
            properties:
                email:
                    type: string
                id:
                    type: string
            required:
                - id
                - email
            type: object
        ErrorDetail:
            additionalProperties: false
            properties:
                location:
                    description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
                    type: string
                message:
                    description: Error message text
                    type: string
                value:
                    description: The value at the given location
            type: object
        ErrorModel:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/ErrorModel.json
                    format: uri
                    readOnly: true
                    type: string
                detail:
                    description: A human-readable explanation specific to this occurrence of the problem.
                    examples:
                        - Property foo is required but is missing.
                    type: string
                errors:
                    description: Optional list of individual error details
                    items:
                        $ref: '#/components/schemas/ErrorDetail'
                    type:
                        - array
                        - "null"
                instance:
                    description: A URI reference that identifies the specific occurrence of the problem.
                    examples:
                        - https://example.com/error-log/abc123
                    format: uri
                    type: string
                status:
                    description: HTTP status code
                    examples:
                        - 400
                    format: int64
                    type: integer
                title:
                    description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
                    examples:
                        - Bad Request
                    type: string
                type:
                    default: about:blank
                    description: A URI reference to human-readable documentation for the error.
                    examples:
                        - https://example.com/errors/example
                    format: uri
                    type: string
            type: object
        JWK:
            additionalProperties: false
            properties:
                alg:
                    type: string
                e:
                    type: string
                kid:
                    type: string
                kty:
                    type: string
                "n":
                    type: string
                use:
                    type: string
            required:
                - kty
                - kid
                - use
                - alg
                - "n"
                - e
            type: object
        JWKSDocument:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/JWKSDocument.json
                    format: uri
                    readOnly: true
                    type: string
                keys:
                    items:
                        $ref: '#/components/schemas/JWK'
                    type:
                        - array
                        - "null"
            required:
                - keys
            type: object
info:
    description: 'The scaffolded Go auth service: the sole minter of JWTs (decision 11) — the four auth endpoints plus the JWKS at /.well-known/jwks.json.'
    title: Starter Auth API
    version: 0.1.0
openapi: 3.1.0
paths:
    /.well-known/jwks.json:
        get:
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/JWKSDocument'
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            summary: Serve the JSON Web Key Set (decision 11)
            tags:
                - jwks
    /auth/login:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AuthCredentialsInputBody'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthTokens'
                    description: OK
                    headers:
                        Set-Cookie:
                            schema:
                                type: string
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            summary: Log in and receive a token pair
            tags:
                - auth
    /auth/logout:
        post:
            parameters:
                - in: cookie
                  name: refresh_token
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AuthRefreshInputBody'
            responses:
                "204":
                    description: No Content
                    headers:
                        Set-Cookie:
                            schema:
                                type: string
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            summary: Revoke the refresh token and clear the cookie
            tags:
                - auth
    /auth/refresh:
        post:
            parameters:
                - in: cookie
                  name: refresh_token
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AuthRefreshInputBody'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthTokens'
                    description: OK
                    headers:
                        Set-Cookie:
                            schema:
                                type: string
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            summary: Rotate the refresh token and issue a new pair
            tags:
                - auth
    /auth/register:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AuthRegisterInputBody'
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthRegisterOutputBody'
                    description: Created
                    headers:
                        Set-Cookie:
                            schema:
                                type: string
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            summary: Register a new user
            tags:
                - auth
`;
}

// openapiMergedYaml is the committed spine: the merge of the two
// partials above (see scripts/merge-openapi.mjs). Kept byte-identical
// to what `task contract:generate` produces — test/generated.test.ts
// is the tripwire.
function openapiMergedYaml(): string {
  return `openapi: 3.1.0
info:
  description: "The scaffolded Go api: items demo behind a JWKS-verified Bearer gate (decision 13/11). Auth lives on apps/api-auth (the sole minter)."
  title: Starter API
  version: 0.1.0
paths:
  /.well-known/jwks.json:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JWKSDocument"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Serve the JSON Web Key Set (decision 11)
      tags:
        - jwks
  /auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthCredentialsInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthTokens"
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Log in and receive a token pair
      tags:
        - auth
  /auth/logout:
    post:
      parameters:
        - in: cookie
          name: refresh_token
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRefreshInputBody"
      responses:
        "204":
          description: No Content
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Revoke the refresh token and clear the cookie
      tags:
        - auth
  /auth/refresh:
    post:
      parameters:
        - in: cookie
          name: refresh_token
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRefreshInputBody"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthTokens"
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Rotate the refresh token and issue a new pair
      tags:
        - auth
  /auth/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRegisterInputBody"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthRegisterOutputBody"
          description: Created
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Register a new user
      tags:
        - auth
  /items:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Item"
                type:
                  - array
                  - "null"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - bearerAuth: []
      summary: List items
      tags:
        - items
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemCreateInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - bearerAuth: []
      summary: Create an item
      tags:
        - items
components:
  schemas:
    AuthCredentialsInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthCredentialsInputBody.json
          format: uri
          readOnly: true
          type: string
        email:
          format: email
          maxLength: 256
          type: string
        password:
          maxLength: 256
          minLength: 1
          type: string
      required:
        - email
        - password
      type: object
    AuthRefreshInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthRefreshInputBody.json
          format: uri
          readOnly: true
          type: string
        refresh:
          type: string
      type: object
    AuthRegisterInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthRegisterInputBody.json
          format: uri
          readOnly: true
          type: string
        email:
          format: email
          maxLength: 256
          type: string
        password:
          maxLength: 256
          minLength: 8
          type: string
      required:
        - email
        - password
      type: object
    AuthRegisterOutputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthRegisterOutputBody.json
          format: uri
          readOnly: true
          type: string
        access:
          type: string
        refresh:
          type: string
        user:
          $ref: "#/components/schemas/AuthUser"
      required:
        - access
        - refresh
        - user
      type: object
    AuthTokens:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthTokens.json
          format: uri
          readOnly: true
          type: string
        access:
          type: string
        refresh:
          type: string
      required:
        - access
        - refresh
      type: object
    AuthUser:
      additionalProperties: false
      properties:
        email:
          type: string
        id:
          type: string
      required:
        - id
        - email
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type:
            - array
            - "null"
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          examples:
            - https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          examples:
            - 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
            - Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          examples:
            - https://example.com/errors/example
          format: uri
          type: string
      type: object
    JWK:
      additionalProperties: false
      properties:
        alg:
          type: string
        e:
          type: string
        kid:
          type: string
        kty:
          type: string
        n:
          type: string
        use:
          type: string
      required:
        - kty
        - kid
        - use
        - alg
        - n
        - e
      type: object
    JWKSDocument:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/JWKSDocument.json
          format: uri
          readOnly: true
          type: string
        keys:
          items:
            $ref: "#/components/schemas/JWK"
          type:
            - array
            - "null"
      required:
        - keys
      type: object
    Item:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/Item.json
          format: uri
          readOnly: true
          type: string
        created_at:
          format: date-time
          type: string
        id:
          type: string
        name:
          maxLength: 200
          type: string
      required:
        - id
        - name
        - created_at
      type: object
    ItemCreateInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ItemCreateInputBody.json
          format: uri
          readOnly: true
          type: string
        name:
          description: Name of the item
          maxLength: 200
          minLength: 1
          type: string
      required:
        - name
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: A short-lived access token (decision 16), minted by apps/api-auth (the sole minter, decision 11); verified locally against its fetched-and-cached JWKS.
      scheme: bearer
      type: http
`;
}

function contractReadmeMs(): string {
  return `// packages/contract — the contract package (decision 9/19).
//
// In the polyglot shapes (3 & 4) this is the *only* shared package:
// the wire-format boundary every side is generated from. There is no
// packages/db or packages/auth — each backend owns its own.
//
// ## Go is the canonical side (decision 19)
//
// Shape 4 (Go-microservices) has TWO Go services, so the committed
// spec is built in three committed steps:
//
//   - \`openapi.api.yaml\`  — generated from apps/api's Go structs
//     (its specgen) — the main api's routes (/items).
//   - \`openapi.auth.yaml\` — generated from apps/api-auth's Go structs
//     (its specgen) — the auth service's routes (/auth/* + the JWKS).
//   - \`openapi.yaml\`      — the MERGED spine: \`scripts/merge-openapi.mjs\`
//     folds the two partials into the single file the TS and Dart
//     clients are generated from.
//
// All three are committed; none are hand-edited. A spec change flows:
//
//  1. change the Go structs on the service that owns the route
//  2. \`task contract:generate\` — regenerates both partials from Go,
//     re-merges openapi.yaml, AND regenerates both clients (TS + Dart)
//  3. commit everything together (the scaffold's tests tripwire this:
//     each service's \`contract_test.go\` proves its committed partial
//     equals its live spec; \`test/generated.test.ts\` proves the merged
//     spec equals the merge of the partials and that the committed
//     client equals the generator's output)
//
// ## Regenerating
//
//     task contract:generate
//
// runs \`go run ./cmd/specgen\` in apps/api (-> openapi.api.yaml) and in
// apps/api-auth (-> openapi.auth.yaml), then
// \`node scripts/merge-openapi.mjs\` (partials -> openapi.yaml), then
// \`node scripts/generate-ts-client.mjs\` (openapi.yaml -> src/) and
// \`node scripts/generate-dart-client.mjs\` (openapi.yaml ->
// clients/dart/lib/). Both clients are generated, never hand-edited —
// the same tripwire test covers them.
`;
}

function mergeOpenapiMjs(): string {
  return `// scripts/merge-openapi.mjs — folds the two Go-generated partial
// specs into the single committed openapi.yaml (decision 19: Go is the
// canonical side; this file is generated, never hand-edited).
//
//   openapi.api.yaml  — apps/api's routes (the main api)
//   openapi.auth.yaml — apps/api-auth's routes (auth + JWKS)
//
// The merge is a UNION, not a resolution: a path may live on exactly
// one service (a collision is a contract error — the two Go apps would
// both own the same route), and a schema name shared by both services
// must be deep-equal (huma's ErrorModel/ErrorDetail). The output is
// what the TS/Dart clients are generated from.
//
// Usage: node scripts/merge-openapi.mjs [api-path] [auth-path] [out-path]
//   defaults: ./openapi.api.yaml ./openapi.auth.yaml ./openapi.yaml

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const apiPath = resolve(process.argv[2] ?? join(root, 'openapi.api.yaml'));
const authPath = resolve(process.argv[3] ?? join(root, 'openapi.auth.yaml'));
const outPath = resolve(process.argv[4] ?? join(root, 'openapi.yaml'));

const api = YAML.parse(readFileSync(apiPath, 'utf8'));
const auth = YAML.parse(readFileSync(authPath, 'utf8'));

const apiPaths = api.paths ?? {};
const authPaths = auth.paths ?? {};

// A path must be owned by exactly one service.
const collisions = Object.keys(apiPaths).filter((p) => authPaths[p]);
if (collisions.length > 0) {
  throw new Error(
    \`merge-openapi: path(s) owned by both services: \${collisions.join(', ')} — the contract is ambiguous\`,
  );
}

const apiSchemas = api.components?.schemas ?? {};
const authSchemas = auth.components?.schemas ?? {};

// Shared schema names must be deep-equal (huma's ErrorModel etc.).
for (const name of Object.keys(authSchemas)) {
  if (apiSchemas[name] && JSON.stringify(authSchemas[name]) !== JSON.stringify(apiSchemas[name])) {
    throw new Error(
      \`merge-openapi: schema "\${name}" differs between the two services — regenerate and commit the partials\`,
    );
  }
}

const apiSecurity = api.components?.securitySchemes ?? {};
const authSecurity = auth.components?.securitySchemes ?? {};

const merged = {
  openapi: '3.1.0',
  info: api.info,
  paths: { ...authPaths, ...apiPaths },
  components: {
    schemas: { ...authSchemas, ...apiSchemas },
    ...(Object.keys(apiSecurity).length > 0 || Object.keys(authSecurity).length > 0
      ? { securitySchemes: { ...authSecurity, ...apiSecurity } }
      : {}),
  },
};

writeFileSync(outPath, YAML.stringify(merged, { indent: 2, lineWidth: 0 }));
console.log(\`merge-openapi: wrote \${outPath}\`);
`;
}

function generatedTestTsMs(): string {
  return `// test/generated.test.ts — proves the Go-as-canonical rule holds in
// the scaffolded project (decision 19) for shape 4
// (Go-microservices): every committed artifact in this package is
// byte-identical to what the generation pipeline produces from the Go
// structs' output. If a spec changes, \`task contract:generate\` must
// be run and its output committed — this file is the tripwire.
//
//   1. openapi.yaml == merge(openapi.api.yaml, openapi.auth.yaml)
//      (the two partials are themselves tripwired by each service's
//      contract_test.go against its live spec)
//   2. the committed TS client == the generator's output from the
//      merged openapi.yaml
//   3. the client covers every route of the merged spec (except
//      well-known infra endpoints, which no client consumes)
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const contractDir = resolve(import.meta.dirname, '..');
const mergeScript = join(contractDir, 'scripts/merge-openapi.mjs');
const generator = join(contractDir, 'scripts/generate-ts-client.mjs');
const partials = {
  api: join(contractDir, 'openapi.api.yaml'),
  auth: join(contractDir, 'openapi.auth.yaml'),
};
const mergedSpec = join(contractDir, 'openapi.yaml');
const committed = {
  'types.ts': join(contractDir, 'src/types.ts'),
  'client.ts': join(contractDir, 'src/client.ts'),
  'index.ts': join(contractDir, 'src/index.ts'),
};

describe('the committed contract is generated, not hand-edited (decision 19, shape 4)', () => {
  it('the merged openapi.yaml equals the merge of the two committed partials', () => {
    const out = mkdtempSync(join(tmpdir(), 'contract-merge-'));
    try {
      execFileSync(process.execPath, [mergeScript, partials.api, partials.auth, join(out, 'merged.yaml')], {
        stdio: 'pipe',
      });
      expect(
        readFileSync(join(out, 'merged.yaml'), 'utf8'),
        \`openapi.yaml is stale — run \\\`task contract:generate\\\` and commit the diff\`,
      ).toBe(readFileSync(mergedSpec, 'utf8'));
    } finally {
      rmSync(out, { recursive: true, force: true });
    }
  });

  it('regenerating the TS client from the merged openapi.yaml changes nothing', () => {
    const out = mkdtempSync(join(tmpdir(), 'contract-regen-'));
    try {
      execFileSync(process.execPath, [generator, mergedSpec, out], { stdio: 'pipe' });
      for (const [name, committedPath] of Object.entries(committed)) {
        expect(readFileSync(join(out, name), 'utf8'), \`\${name} is stale — run \\\`task contract:generate\\\` and commit the diff\`)
          .toBe(readFileSync(committedPath, 'utf8'));
      }
    } finally {
      rmSync(out, { recursive: true, force: true });
    }
  });

  it('regenerating the Dart client from the merged openapi.yaml changes nothing', () => {
    const dartGenerator = join(contractDir, 'scripts/generate-dart-client.mjs');
    const out = mkdtempSync(join(tmpdir(), 'contract-regen-dart-'));
    try {
      execFileSync(process.execPath, [dartGenerator, mergedSpec, join(out, 'openapi_client.dart')], { stdio: 'pipe' });
      expect(
        readFileSync(join(out, 'openapi_client.dart'), 'utf8'),
        \`openapi_client.dart is stale — run \\\`task contract:generate\\\` and commit the diff\`,
      ).toBe(readFileSync(join(contractDir, 'clients/dart/lib/openapi_client.dart'), 'utf8'));
    } finally {
      rmSync(out, { recursive: true, force: true });
    }
  });

  it('the client covers every route of the merged spec (well-known infra excluded)', () => {
    const client = readFileSync(committed['client.ts'], 'utf8');
    for (const ep of ['/items', '/auth/register', '/auth/login', '/auth/refresh', '/auth/logout']) {
      expect(client, \`client.ts should expose \${ep}\`).toContain(\`'\${ep}'\`);
    }
    // The JWKS endpoint is machine-to-machine infra consumed by the
    // api, not by generated clients — the generator skips well-known
    // paths, so the client must NOT contain it.
    expect(client).not.toContain('/.well-known');
    // The items routes are authenticated (Bearer) per the spec's
    // security requirement.
    expect(client).toMatch(/GET \\/items \\(requires Bearer access token\\)/);
  });
});
`;
}

function clientTypesTsMs(): string {
  return `// GENERATED by scripts/generate-ts-client.mjs — do not edit by hand.
// Regenerate with \`task contract:generate\` after regenerating
// openapi.yaml from the Go structs (decision 19: Go is canonical,
// clients are downstream).

export interface AuthCredentialsInputBody {
  email: string;
  password: string;
}

export interface AuthRefreshInputBody {
  refresh?: string;
}

export interface AuthRegisterInputBody {
  email: string;
  password: string;
}

export interface AuthRegisterOutputBody {
  access: string;
  refresh: string;
  user: AuthUser;
}

export interface AuthTokens {
  access: string;
  refresh: string;
}

export interface AuthUser {
  email: string;
  id: string;
}

export interface ErrorDetail {
  location?: string;
  message?: string;
  value?: unknown;
}

export interface ErrorModel {
  detail?: string;
  errors?: ErrorDetail[];
  instance?: string;
  status?: number;
  title?: string;
  type?: string;
}

export interface JWK {
  alg: string;
  e: string;
  kid: string;
  kty: string;
  n: string;
  use: string;
}

export interface JWKSDocument {
  keys: JWK[];
}

export interface Item {
  created_at: string;
  id: string;
  name: string;
}

export interface ItemCreateInputBody {
  name: string;
}
`;
}

function clientIndexTsMs(): string {
  return `// GENERATED by scripts/generate-ts-client.mjs — do not edit by hand.
// Regenerate with \`task contract:generate\` after regenerating
// openapi.yaml from the Go structs (decision 19: Go is canonical,
// clients are downstream).

export type {
  AuthCredentialsInputBody,
  AuthRefreshInputBody,
  AuthRegisterInputBody,
  AuthRegisterOutputBody,
  AuthTokens,
  AuthUser,
  ErrorDetail,
  ErrorModel,
  JWK,
  JWKSDocument,
  Item,
  ItemCreateInputBody,
} from './types';
export { createClient, type ClientOptions } from './client';`;
}

function dartClientMs(): string {
  return `// GENERATED by scripts/generate-dart-client.mjs — do not edit by hand.
// Regenerate with \`task contract:generate\` after regenerating
// openapi.yaml from the Go structs (decision 19: Go is canonical,
// clients are downstream). Consumed by the Flutter mobile (ticket 17).

import 'dart:convert';

import 'package:http/http.dart' as http;

/// AuthCredentialsInputBody — a schema of the committed openapi.yaml.
class AuthCredentialsInputBody {
  const AuthCredentialsInputBody({
    required this.email,
    required this.password,
  });

  final String email;
  final String password;

  factory AuthCredentialsInputBody.fromJson(Map<String, dynamic> json) => AuthCredentialsInputBody(
        email: json['email'] as String,
        password: json['password'] as String,
      );

  Map<String, dynamic> toJson() => {
        'email': email,
        'password': password,
      };
}

/// AuthRefreshInputBody — a schema of the committed openapi.yaml.
class AuthRefreshInputBody {
  const AuthRefreshInputBody({
    this.refresh,
  });

  final String? refresh;

  factory AuthRefreshInputBody.fromJson(Map<String, dynamic> json) => AuthRefreshInputBody(
        refresh: json['refresh'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'refresh': refresh,
      };
}

/// AuthRegisterInputBody — a schema of the committed openapi.yaml.
class AuthRegisterInputBody {
  const AuthRegisterInputBody({
    required this.email,
    required this.password,
  });

  final String email;
  final String password;

  factory AuthRegisterInputBody.fromJson(Map<String, dynamic> json) => AuthRegisterInputBody(
        email: json['email'] as String,
        password: json['password'] as String,
      );

  Map<String, dynamic> toJson() => {
        'email': email,
        'password': password,
      };
}

/// AuthRegisterOutputBody — a schema of the committed openapi.yaml.
class AuthRegisterOutputBody {
  const AuthRegisterOutputBody({
    required this.access,
    required this.refresh,
    required this.user,
  });

  final String access;
  final String refresh;
  final AuthUser user;

  factory AuthRegisterOutputBody.fromJson(Map<String, dynamic> json) => AuthRegisterOutputBody(
        access: json['access'] as String,
        refresh: json['refresh'] as String,
        user: AuthUser.fromJson(json['user'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'access': access,
        'refresh': refresh,
        'user': user,
      };
}

/// AuthTokens — a schema of the committed openapi.yaml.
class AuthTokens {
  const AuthTokens({
    required this.access,
    required this.refresh,
  });

  final String access;
  final String refresh;

  factory AuthTokens.fromJson(Map<String, dynamic> json) => AuthTokens(
        access: json['access'] as String,
        refresh: json['refresh'] as String,
      );

  Map<String, dynamic> toJson() => {
        'access': access,
        'refresh': refresh,
      };
}

/// AuthUser — a schema of the committed openapi.yaml.
class AuthUser {
  const AuthUser({
    required this.email,
    required this.id,
  });

  final String email;
  final String id;

  factory AuthUser.fromJson(Map<String, dynamic> json) => AuthUser(
        email: json['email'] as String,
        id: json['id'] as String,
      );

  Map<String, dynamic> toJson() => {
        'email': email,
        'id': id,
      };
}

/// ErrorDetail — a schema of the committed openapi.yaml.
class ErrorDetail {
  const ErrorDetail({
    this.location,
    this.message,
    this.value,
  });

  final String? location;
  final String? message;
  final dynamic value;

  factory ErrorDetail.fromJson(Map<String, dynamic> json) => ErrorDetail(
        location: json['location'] as String?,
        message: json['message'] as String?,
        value: json['value'],
      );

  Map<String, dynamic> toJson() => {
        'location': location,
        'message': message,
        'value': value,
      };
}

/// ErrorModel — a schema of the committed openapi.yaml.
class ErrorModel {
  const ErrorModel({
    this.detail,
    this.errors,
    this.instance,
    this.status,
    this.title,
    this.type,
  });

  final String? detail;
  final List<ErrorDetail>? errors;
  final String? instance;
  final int? status;
  final String? title;
  final String? type;

  factory ErrorModel.fromJson(Map<String, dynamic> json) => ErrorModel(
        detail: json['detail'] as String?,
        errors: json['errors'] == null ? null : (json['errors'] as List).map((e) => ErrorDetail.fromJson(e as Map<String, dynamic>)).toList(),
        instance: json['instance'] as String?,
        status: json['status'] as int?,
        title: json['title'] as String?,
        type: json['type'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'detail': detail,
        'errors': errors?.map((e) => e.toJson()).toList(),
        'instance': instance,
        'status': status,
        'title': title,
        'type': type,
      };
}

/// JWK — a schema of the committed openapi.yaml.
class JWK {
  const JWK({
    required this.alg,
    required this.e,
    required this.kid,
    required this.kty,
    required this.n,
    required this.use,
  });

  final String alg;
  final String e;
  final String kid;
  final String kty;
  final String n;
  final String use;

  factory JWK.fromJson(Map<String, dynamic> json) => JWK(
        alg: json['alg'] as String,
        e: json['e'] as String,
        kid: json['kid'] as String,
        kty: json['kty'] as String,
        n: json['n'] as String,
        use: json['use'] as String,
      );

  Map<String, dynamic> toJson() => {
        'alg': alg,
        'e': e,
        'kid': kid,
        'kty': kty,
        'n': n,
        'use': use,
      };
}

/// JWKSDocument — a schema of the committed openapi.yaml.
class JWKSDocument {
  const JWKSDocument({
    required this.keys,
  });

  final List<JWK>? keys;

  factory JWKSDocument.fromJson(Map<String, dynamic> json) => JWKSDocument(
        keys: json['keys'] == null ? null : (json['keys'] as List).map((e) => JWK.fromJson(e as Map<String, dynamic>)).toList(),
      );

  Map<String, dynamic> toJson() => {
        'keys': keys?.map((e) => e.toJson()).toList(),
      };
}

/// Item — a schema of the committed openapi.yaml.
class Item {
  const Item({
    required this.createdAt,
    required this.id,
    required this.name,
  });

  final DateTime createdAt;
  final String id;
  final String name;

  factory Item.fromJson(Map<String, dynamic> json) => Item(
        createdAt: DateTime.parse(json['created_at'] as String),
        id: json['id'] as String,
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'created_at': createdAt.toIso8601String(),
        'id': id,
        'name': name,
      };
}

/// ItemCreateInputBody — a schema of the committed openapi.yaml.
class ItemCreateInputBody {
  const ItemCreateInputBody({
    required this.name,
  });

  final String name;

  factory ItemCreateInputBody.fromJson(Map<String, dynamic> json) => ItemCreateInputBody(
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'name': name,
      };
}

/// A typed client over the committed openapi.yaml (decision 19).
class OpenApiClient {
  OpenApiClient({
    required this.baseUrl,
    this.accessToken,
    http.Client? httpClient,
  }) : _http = httpClient ?? http.Client();

  final String baseUrl;

  /// The Bearer access token attached to protected calls (decision 16/23).
  String? accessToken;

  final http.Client _http;

  Map<String, String> _headers({required bool authenticated}) => {
        'Content-Type': 'application/json',
        if (authenticated && accessToken != null) 'Authorization': 'Bearer $accessToken',
      };

  Future<dynamic> _send(
    String method,
    String path, {
    Map<String, dynamic>? body,
    bool authenticated = false,
  }) async {
    final request = http.Request(method, Uri.parse('$baseUrl$path'))
      ..headers.addAll(_headers(authenticated: authenticated));
    if (body != null) request.body = jsonEncode(body);
    final response = await _http.send(request);
    final text = await response.stream.bytesToString();
    if (response.statusCode >= 400) {
      var message = '$method $path -> \${response.statusCode}';
      if (text.isNotEmpty) {
        try {
          final decoded = jsonDecode(text) as Map<String, dynamic>;
          message = decoded['detail'] as String? ?? message;
        } catch (_) {
          // non-JSON error body; keep the status message
        }
      }
      throw OpenApiException(response.statusCode, message);
    }
    if (text.isEmpty) return null;
    return jsonDecode(text);
  }

  /// POST /auth/login
  Future<AuthTokens> login(AuthCredentialsInputBody input) async {
    final json = await _send('POST', '/auth/login', body: input.toJson());
    return AuthTokens.fromJson(json as Map<String, dynamic>);
  }

  /// POST /auth/logout
  Future<void> logout(AuthRefreshInputBody input) async {
    await _send('POST', '/auth/logout', body: input.toJson());
  }

  /// POST /auth/refresh
  Future<AuthTokens> refresh(AuthRefreshInputBody input) async {
    final json = await _send('POST', '/auth/refresh', body: input.toJson());
    return AuthTokens.fromJson(json as Map<String, dynamic>);
  }

  /// POST /auth/register
  Future<AuthRegisterOutputBody> register(AuthRegisterInputBody input) async {
    final json = await _send('POST', '/auth/register', body: input.toJson());
    return AuthRegisterOutputBody.fromJson(json as Map<String, dynamic>);
  }

  /// GET /items (requires Bearer access token)
  Future<List<Item>> listItems() async {
    final json = await _send('GET', '/items', authenticated: true);
    return (json as List).map((e) => Item.fromJson(e as Map<String, dynamic>)).toList();
  }

  /// POST /items (requires Bearer access token)
  Future<Item> createItem(ItemCreateInputBody input) async {
    final json = await _send('POST', '/items', body: input.toJson(), authenticated: true);
    return Item.fromJson(json as Map<String, dynamic>);
  }

}

/// Thrown for non-2xx responses.
class OpenApiException implements Exception {
  OpenApiException(this.statusCode, this.message);

  final int statusCode;
  final String message;

  @override
  String toString() => 'OpenApiException($statusCode): $message';
}
`;
}

export { openapiApiYaml, openapiAuthYaml, openapiMergedYaml, contractReadmeMs, mergeOpenapiMjs, generatedTestTsMs, clientTypesTsMs, clientIndexTsMs, dartClientMs };
