// Materializer: the shape-4 + AI-on additions to packages/contract
// (issue #16).
//
// Decision 9: in the polyglot shapes packages/contract is the ONLY
// package — the wire-format boundary every side is generated from.
// Shape 4 + AI adds a THIRD contract surface, owned by a different
// canonical side:
//
//   openapi.ai.yaml — the AI service's spec, GENERATED by the Python
//                     FastAPI app (scripts/export_openapi.py in
//                     apps/ai) and committed. Python is the canonical
//                     side of the AI service's own contract.
//   clients/go/     — a stdlib-only Go client GENERATED from
//                     openapi.ai.yaml (scripts/generate-go-client.mjs),
//                     consumed by apps/api via a local go.mod replace
//                     (decision 5: the AI service is called by the Go
//                     api through this client — never raw HTTP).
//
// The AI spec is NOT merged into openapi.yaml: that merged file is
// the TS/Dart client spine for the web-facing surface (api + auth).
// The AI service is machine-to-machine (called by the Go api), so its
// contract lives beside the merged spine and is consumed by the Go
// client — the web reaches AI only through apps/api's /ai surface
// (which apps/api's specgen folds into openapi.api.yaml).
//
// Tripwires: apps/ai's tests/test_contract.py proves the committed
// openapi.ai.yaml equals the live FastAPI spec; this package's
// test/generated-go.test.ts proves the committed Go client equals the
// generator's output. A spec change flows Python models -> export ->
// Go client regen -> commit.
//
// Per issue #27 the materializer is split by workspace; this module
// owns every shape-4-AI file written into packages/contract.

import { join } from 'node:path';
import { type ProjectContext, writeFileRecursive } from './_shared.js';

export async function writeGoContractMsAi(ctx: ProjectContext): Promise<void> {
  const { targetDir } = ctx;

  const contractDir = join(targetDir, 'packages/contract');
  // The AI service's own contract surface (Python-generated spec + the
  // Go client apps/api consumes).
  await writeFileRecursive(join(contractDir, 'openapi.ai.yaml'), openapiAiYaml());
  await writeFileRecursive(join(contractDir, 'scripts/generate-go-client.mjs'), generateGoClientMjs());
  await writeFileRecursive(join(contractDir, 'clients/go/go.mod'), goClientGoMod());
  await writeFileRecursive(join(contractDir, 'clients/go/client.go'), goClientGo());
  await writeFileRecursive(join(contractDir, 'clients/go/README.md'), goClientReadme());
  await writeFileRecursive(join(contractDir, 'test/generated-go.test.ts'), generatedGoTestTs());

  // AI-on OVERRIDES of the web-facing spine (the base shape-4
  // materializer wrote them first): the api's partial spec now
  // documents the /ai proxy routes, the merged spec + TS client
  // follow, and the generated-test tripwire covers the AI surface.
  await writeFileRecursive(join(contractDir, 'openapi.api.yaml'), openapiApiYamlAi());
  await writeFileRecursive(join(contractDir, 'openapi.yaml'), openapiMergedYamlAi());
  await writeFileRecursive(join(contractDir, 'src/types.ts'), clientTypesTsAi());
  await writeFileRecursive(join(contractDir, 'src/client.ts'), clientTsAi());
  await writeFileRecursive(join(contractDir, 'src/index.ts'), clientIndexTsAi());
  await writeFileRecursive(join(contractDir, 'test/generated.test.ts'), generatedTestTsAi());
}

// openapiAiYaml is the committed AI service spec — GENERATED by
// apps/ai's scripts/export_openapi.py (FastAPI's /openapi.json). It is
// kept byte-identical to what that script produces; the AI service's
// tests/test_contract.py is the tripwire. Never hand-edit: change the
// Python models and regenerate.
// openapiAiYaml is the committed AI service spec — GENERATED by
// apps/ai's scripts/export_openapi.py (FastAPI's /openapi.json). It is
// kept byte-identical to what that script produces; the AI service's
// tests/test_contract.py is the tripwire. Never hand-edit: change the
// Python models and regenerate.
// openapiAiYaml is the committed AI service spec — GENERATED by
// apps/ai's scripts/export_openapi.py (FastAPI's /openapi.json). It is
// kept byte-identical to what that script produces; the AI service's
// tests/test_contract.py is the tripwire. Never hand-edit: change the
// Python models and regenerate.
function openapiAiYaml(): string {
  return `openapi: 3.1.0
info:
  title: Starter AI API
  description: 'The scaffolded Python/FastAPI AI service (shape 4, decision 5/20): composable AI primitives — chat completion (with streaming), embeddings, a VectorStore interface, and tool/function calling — over their own contract surface. Called by apps/api via the generated Go client. No example composition is shipped (decision 20).'
  version: 0.1.0
paths:
  /ai/chat/completions:
    post:
      tags:
      - ai
      summary: Chat completion (with streaming)
      description: 'Complete a conversation. When request.stream is true the

        service responds with a text/event-stream of completion chunks

        instead of the JSON completion modeled by the contract — the

        streaming form of the same primitive (decision 20).'
      operationId: chat_completions_ai_chat_completions_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatCompletionRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatCompletionResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/embeddings:
    post:
      tags:
      - ai
      summary: Embeddings
      description: Embed text — a single string or a list of strings.
      operationId: embeddings_ai_embeddings_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmbeddingsRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmbeddingsResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/vector-store/upsert:
    post:
      tags:
      - ai
      summary: Upsert vectors into the VectorStore
      description: Insert or replace vectors by id.
      operationId: vector_store_upsert_ai_vector_store_upsert_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VectorStoreUpsertRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VectorStoreUpsertResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/vector-store/search:
    post:
      tags:
      - ai
      summary: Search the VectorStore by cosine similarity
      description: Return the top_k nearest neighbours to the query vector.
      operationId: vector_store_search_ai_vector_store_search_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VectorStoreSearchRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VectorStoreSearchResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ChatChoice:
      properties:
        index:
          type: integer
          title: Index
        message:
          $ref: '#/components/schemas/ChatMessage'
        finish_reason:
          anyOf:
          - type: string
          - type: 'null'
          title: Finish Reason
          description: 'Why the completion stopped: stop, length, tool_calls, ...'
      type: object
      required:
      - index
      - message
      title: ChatChoice
      description: One completion candidate.
    ChatCompletionRequest:
      properties:
        model:
          anyOf:
          - type: string
          - type: 'null'
          title: Model
          description: Model id. Defaults to the service's configured OPENAI_MODEL.
        messages:
          items:
            $ref: '#/components/schemas/ChatMessage'
          type: array
          minItems: 1
          title: Messages
          description: The conversation so far.
        temperature:
          anyOf:
          - type: number
            maximum: 2.0
            minimum: 0.0
          - type: 'null'
          title: Temperature
          description: Sampling temperature.
        stream:
          type: boolean
          title: Stream
          description: When true the service responds with a text/event-stream of completion chunks (SSE). The OpenAPI contract models the non-streaming JSON completion; streaming is the SSE form of the same primitive.
          default: false
        tools:
          anyOf:
          - items:
              $ref: '#/components/schemas/ToolDefinition'
            type: array
          - type: 'null'
          title: Tools
          description: Functions the model may call (tool/function calling).
        tool_choice:
          anyOf:
          - type: string
          - type: 'null'
          title: Tool Choice
          description: 'Which tool to force: ''auto'', ''none'', or a tool name.'
      type: object
      required:
      - messages
      title: ChatCompletionRequest
      description: The body of POST /ai/chat/completions.
    ChatCompletionResponse:
      properties:
        id:
          type: string
          title: Id
        model:
          type: string
          title: Model
        choices:
          items:
            $ref: '#/components/schemas/ChatChoice'
          type: array
          title: Choices
        usage:
          anyOf:
          - $ref: '#/components/schemas/Usage'
          - type: 'null'
      type: object
      required:
      - id
      - model
      - choices
      title: ChatCompletionResponse
      description: The body of POST /ai/chat/completions (stream=false).
    ChatMessage:
      properties:
        role:
          type: string
          title: Role
          description: 'The role of the message author: system, user, assistant, or tool.'
        content:
          anyOf:
          - type: string
          - type: 'null'
          title: Content
          description: The text content of the message.
        tool_calls:
          anyOf:
          - items:
              $ref: '#/components/schemas/ToolCall'
            type: array
          - type: 'null'
          title: Tool Calls
          description: Tool calls made by an assistant message (tool/function calling).
      type: object
      required:
      - role
      title: ChatMessage
      description: One message of the conversation.
    EmbeddingData:
      properties:
        embedding:
          items:
            type: number
          type: array
          title: Embedding
          description: The embedding vector.
        index:
          type: integer
          title: Index
          description: The index of the input this embedding corresponds to.
      type: object
      required:
      - embedding
      - index
      title: EmbeddingData
      description: One embedded input.
    EmbeddingsRequest:
      properties:
        model:
          anyOf:
          - type: string
          - type: 'null'
          title: Model
          description: Model id. Defaults to the service's configured OPENAI_EMBEDDINGS_MODEL.
        input:
          anyOf:
          - type: string
          - items:
              type: string
            type: array
          title: Input
          description: Text to embed — a single string or a list of strings.
      type: object
      required:
      - input
      title: EmbeddingsRequest
      description: The body of POST /ai/embeddings.
    EmbeddingsResponse:
      properties:
        model:
          type: string
          title: Model
        data:
          items:
            $ref: '#/components/schemas/EmbeddingData'
          type: array
          title: Data
      type: object
      required:
      - model
      - data
      title: EmbeddingsResponse
      description: The body of POST /ai/embeddings.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ToolCall:
      properties:
        id:
          type: string
          title: Id
          description: The id of the tool call.
        name:
          type: string
          title: Name
          description: The name of the tool to call.
        arguments:
          type: string
          title: Arguments
          description: JSON-encoded arguments for the tool.
      type: object
      required:
      - id
      - name
      - arguments
      title: ToolCall
      description: A concrete tool invocation returned by the model.
    ToolDefinition:
      properties:
        name:
          type: string
          title: Name
          description: The name of the tool the model may call.
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
          description: A description of what the tool does — the model uses it to decide when to call it.
        parameters:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Parameters
          description: The JSON Schema of the tool's parameters.
      type: object
      required:
      - name
      title: ToolDefinition
      description: A function the model may call (tool/function calling, decision 20).
    Usage:
      properties:
        prompt_tokens:
          type: integer
          title: Prompt Tokens
        completion_tokens:
          type: integer
          title: Completion Tokens
        total_tokens:
          type: integer
          title: Total Tokens
      type: object
      required:
      - prompt_tokens
      - completion_tokens
      - total_tokens
      title: Usage
      description: Token accounting for a completion.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    VectorRecord:
      properties:
        id:
          type: string
          title: Id
          description: The unique id of the record.
        vector:
          items:
            type: number
          type: array
          title: Vector
          description: The embedding vector.
        metadata:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Metadata
          description: Arbitrary metadata stored alongside the vector.
      type: object
      required:
      - id
      - vector
      title: VectorRecord
      description: A vector to store (upsert) or a stored vector's metadata.
    VectorStoreSearchRequest:
      properties:
        vector:
          items:
            type: number
          type: array
          title: Vector
          description: The query vector.
        top_k:
          type: integer
          maximum: 100.0
          minimum: 1.0
          title: Top K
          description: How many nearest neighbours to return.
          default: 5
      type: object
      required:
      - vector
      title: VectorStoreSearchRequest
      description: The body of POST /ai/vector-store/search.
    VectorStoreSearchResponse:
      properties:
        results:
          items:
            $ref: '#/components/schemas/VectorStoreSearchResult'
          type: array
          title: Results
      type: object
      required:
      - results
      title: VectorStoreSearchResponse
      description: The body of POST /ai/vector-store/search.
    VectorStoreSearchResult:
      properties:
        id:
          type: string
          title: Id
        score:
          type: number
          title: Score
          description: Cosine similarity — higher is closer (1.0 = identical direction).
        metadata:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Metadata
      type: object
      required:
      - id
      - score
      title: VectorStoreSearchResult
      description: One nearest-neighbour hit.
    VectorStoreUpsertRequest:
      properties:
        vectors:
          items:
            $ref: '#/components/schemas/VectorRecord'
          type: array
          minItems: 1
          title: Vectors
          description: Records to insert or replace by id.
      type: object
      required:
      - vectors
      title: VectorStoreUpsertRequest
      description: The body of POST /ai/vector-store/upsert.
    VectorStoreUpsertResponse:
      properties:
        count:
          type: integer
          title: Count
          description: How many records were upserted.
      type: object
      required:
      - count
      title: VectorStoreUpsertResponse
      description: The body of POST /ai/vector-store/upsert.
`;
}
function generateGoClientMjs(): string {
  return `// scripts/generate-go-client.mjs — regenerates clients/go/client.go
// (a stdlib-only Go client) from the committed openapi.ai.yaml — the
// AI service's Python-generated spec (decision 9: the contract is the
// spine; here Python is the canonical side of the AI service's own
// contract). apps/api consumes this client through a local go.mod
// replace — it is the ONLY way apps/api talks to apps/ai (decision 5:
// never raw HTTP).
//
// The generator is intentionally small and dependency-light (only
// \`yaml\` for parsing): the emitted client is typed request/response
// structs plus one \`do\`-style request helper, nothing more.
// Regenerating must produce a byte-identical diff — the scaffold's
// tests assert that (test/generated-go.test.ts). The emitted structs
// are gofmt-aligned (name column, type column, tag column).
//
// Usage: node scripts/generate-go-client.mjs [spec-path] [out-dir]
//   spec-path defaults to ./openapi.ai.yaml
//   out-dir   defaults to ./clients/go

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const specPath = resolve(process.argv[2] ?? join(root, 'openapi.ai.yaml'));
const outDir = resolve(process.argv[3] ?? join(root, 'clients/go'));

const spec = YAML.parse(readFileSync(specPath, 'utf8'));

const header = [
  '// GENERATED by scripts/generate-go-client.mjs — do not edit by hand.',
  '// Regenerate with \`task contract:generate\` after regenerating',
  '// openapi.ai.yaml from the Python service (decision 9: Python is',
  '// the canonical side of the AI service contract).',
  '',
  'package aiclient',
  '',
  'import (',
  '\t"bytes"',
  '\t"context"',
  '\t"encoding/json"',
  '\t"fmt"',
  '\t"io"',
  '\t"net/http"',
  '\t"strings"',
  '\t"time"',
  ')',
  '',
].join('\\n');

// ---- type mapping ----------------------------------------------------------

// goType maps a JSON Schema to a Go type name. anyOf containing a
// 'null' variant is an optional field — the non-null variant's type is
// returned (pointer-ness is decided by the caller).
function goType(schema, schemas) {
  if (!schema) return 'any';
  if (schema.$ref) return schema.$ref.split('/').pop();
  if (schema.anyOf) {
    const nonNull = schema.anyOf.filter((s) => s.type !== 'null');
    if (nonNull.length === 1) return goType(nonNull[0], schemas);
    // Two non-null variants (e.g. string | string[]) is a union the
    // starter's typed client represents as the Go any.
    return 'any';
  }
  const t = schema.type;
  switch (t) {
    case 'string': return 'string';
    case 'integer': return 'int64';
    case 'number': return 'float64';
    case 'boolean': return 'bool';
    case 'array': return '[]' + goType(schema.items, schemas);
    case 'object': return 'map[string]any';
    default: return 'any';
  }
}

// isOptional reports whether a property may be absent on the wire: it
// is not in the required list and has no default (a default means the
// service always has a value to fall back to).
function isOptional(schema, required) {
  if (required) return false;
  if (schema.default !== undefined) return false;
  if (schema.anyOf) return schema.anyOf.some((s) => s.type === 'null');
  return true;
}

// fieldGoType returns the declared Go type for a property. Optional
// scalars and refs become pointers (nil = absent, omitted by
// omitempty); slices, maps, and unions stay value-typed.
function fieldGoType(schema, schemas, required) {
  const base = goType(schema, schemas);
  if (!isOptional(schema, required)) return base;
  if (base === 'any' || base.startsWith('[]') || base === 'map[string]any') return base;
  return '*' + base;
}

function goFieldName(prop) {
  // snake_case -> PascalCase ('tool_calls' -> 'ToolCalls').
  return prop.split('_').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}

function generateStructs(schemas) {
  const lines = [header];
  for (const [name, schema] of Object.entries(schemas)) {
    // FastAPI's default 422 validation schemas are plumbing, not part
    // of the AI service's primitive contract.
    if (name === 'HTTPValidationError' || name === 'ValidationError') continue;
    if (schema.type !== 'object') continue;
    if (schema.description) {
      for (const l of schema.description.split('\\n')) lines.push('// ' + l);
    }
    const fields = [];
    for (const [prop, propSchema] of Object.entries(schema.properties ?? {})) {
      const required = (schema.required ?? []).includes(prop);
      fields.push({
        name: goFieldName(prop),
        type: fieldGoType(propSchema, schemas, required),
        tag: required ? prop : prop + ',omitempty',
      });
    }
    // gofmt alignment: pad the name column to the longest name, then
    // the type column to the longest type (each +1 space).
    const nameWidth = Math.max(...fields.map((f) => f.name.length));
    const typeWidth = Math.max(...fields.map((f) => f.type.length));
    lines.push('type ' + name + ' struct {');
    for (const f of fields) {
      lines.push('\t' + f.name.padEnd(nameWidth) + ' ' + f.type.padEnd(typeWidth) + ' \`json:"' + f.tag + '"\`');
    }
    lines.push('}', '');
  }
  return lines.join('\\n');
}

// ---- client ----------------------------------------------------------------

function methodName(path) {
  // '/ai/vector-store/upsert' -> 'VectorStoreUpsert' (skip the /ai
  // root; non-alphanumeric segments are CamelCased and joined).
  const segs = path.split('/').filter(Boolean).slice(1);
  return segs
    .map((s) => s.split(/[^a-zA-Z0-9]/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(''))
    .join('');
}

function operationTypes(op, schemas) {
  const req = op.requestBody?.content?.['application/json']?.schema;
  const resp = op.responses?.['200']?.content?.['application/json']?.schema;
  return {
    reqName: req?.$ref ? req.$ref.split('/').pop() : null,
    respName: resp?.$ref ? resp.$ref.split('/').pop() : null,
  };
}

function generateClient(paths, schemas) {
  const lines = [];
  lines.push('// HTTPError carries a non-2xx response from the AI service.');
  lines.push('type HTTPError struct {');
  lines.push('\tStatus int');
  lines.push('\tBody   string');
  lines.push('}');
  lines.push('');
  lines.push('func (e *HTTPError) Error() string {');
  lines.push('\tif e.Body == "" {');
  lines.push('\t\treturn fmt.Sprintf("aiclient: %s", http.StatusText(e.Status))');
  lines.push('\t}');
  lines.push('\treturn fmt.Sprintf("aiclient: %s: %s", http.StatusText(e.Status), e.Body)');
  lines.push('}');
  lines.push('');
  lines.push('// Client is a typed Go client over the committed openapi.ai.yaml.');
  lines.push('type Client struct {');
  lines.push('\tbaseURL string');
  lines.push('\thttp    *http.Client');
  lines.push('}');
  lines.push('');
  lines.push('// NewClient wires a client to the AI service base URL, e.g.');
  lines.push('// http://localhost:3200 (AI_SERVICE_URL).');
  lines.push('func NewClient(baseURL string) *Client {');
  lines.push('\treturn &Client{baseURL: strings.TrimSuffix(baseURL, "/"), http: &http.Client{Timeout: 30 * time.Second}}');
  lines.push('}');
  lines.push('');
  lines.push('// do performs one JSON request/response round-trip.');
  lines.push('func (c *Client) do(ctx context.Context, method, path string, body, out any) error {');
  lines.push('\tvar reader io.Reader');
  lines.push('\tif body != nil {');
  lines.push('\t\traw, err := json.Marshal(body)');
  lines.push('\t\tif err != nil {');
  lines.push('\t\t\treturn fmt.Errorf("aiclient: marshal %s %s: %w", method, path, err)');
  lines.push('\t\t}');
  lines.push('\t\treader = bytes.NewReader(raw)');
  lines.push('\t}');
  lines.push('\treq, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, reader)');
  lines.push('\tif err != nil {');
  lines.push('\t\treturn fmt.Errorf("aiclient: %s %s: %w", method, path, err)');
  lines.push('\t}');
  lines.push('\tif body != nil {');
  lines.push('\t\treq.Header.Set("Content-Type", "application/json")');
  lines.push('\t}');
  lines.push('\tresp, err := c.http.Do(req)');
  lines.push('\tif err != nil {');
  lines.push('\t\treturn fmt.Errorf("aiclient: %s %s: %w", method, path, err)');
  lines.push('\t}');
  lines.push('\tdefer resp.Body.Close()');
  lines.push('\tif resp.StatusCode >= 400 {');
  lines.push('\t\traw, _ := io.ReadAll(resp.Body)');
  lines.push('\t\treturn &HTTPError{Status: resp.StatusCode, Body: strings.TrimSpace(string(raw))}');
  lines.push('\t}');
  lines.push('\tif out != nil {');
  lines.push('\t\tif err := json.NewDecoder(resp.Body).Decode(out); err != nil {');
  lines.push('\t\t\treturn fmt.Errorf("aiclient: decode %s %s: %w", method, path, err)');
  lines.push('\t\t}');
  lines.push('\t}');
  lines.push('\treturn nil');
  lines.push('}');
  lines.push('');
  for (const [path, item] of Object.entries(paths)) {
    for (const [method, op] of Object.entries(item)) {
      if (method !== 'post') continue;
      const { reqName, respName } = operationTypes(op, schemas);
      const name = methodName(path);
      lines.push('// ' + name.toUpperCase() + ' calls ' + method.toUpperCase() + ' ' + path + '.');
      lines.push('func (c *Client) ' + name + '(ctx context.Context, req ' + reqName + ') (*' + respName + ', error) {');
      lines.push('\tvar out ' + respName);
      lines.push('\tif err := c.do(ctx, http.MethodPost, "' + path + '", req, &out); err != nil {');
      lines.push('\t\treturn nil, err');
      lines.push('\t}');
      lines.push('\treturn &out, nil');
      lines.push('}');
      lines.push('');
    }
  }
  return lines.join('\\n');
}

// ---- emit ------------------------------------------------------------------

const schemas = spec.components?.schemas ?? {};
const paths = spec.paths ?? {};

const src = generateStructs(schemas) + '\\n' + generateClient(paths, schemas);

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'client.go'), src);

console.log('generate-go-client: wrote ' + join(outDir, 'client.go'));
`;
}
function goClientGoMod(): string {
  return `module starter/contract/ai-client

go 1.25.0
`;
}
// goClientGo is the committed output of scripts/generate-go-client.mjs
// over the committed openapi.ai.yaml. test/generated-go.test.ts is the
// tripwire.
function goClientGo(): string {
  return `// GENERATED by scripts/generate-go-client.mjs — do not edit by hand.
// Regenerate with \`task contract:generate\` after regenerating
// openapi.ai.yaml from the Python service (decision 9: Python is
// the canonical side of the AI service contract).

package aiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// One completion candidate.
type ChatChoice struct {
	Index        int64       \`json:"index"\`
	Message      ChatMessage \`json:"message"\`
	FinishReason *string     \`json:"finish_reason,omitempty"\`
}

// The body of POST /ai/chat/completions.
type ChatCompletionRequest struct {
	Model       *string          \`json:"model,omitempty"\`
	Messages    []ChatMessage    \`json:"messages"\`
	Temperature *float64         \`json:"temperature,omitempty"\`
	Stream      bool             \`json:"stream,omitempty"\`
	Tools       []ToolDefinition \`json:"tools,omitempty"\`
	ToolChoice  *string          \`json:"tool_choice,omitempty"\`
}

// The body of POST /ai/chat/completions (stream=false).
type ChatCompletionResponse struct {
	Id      string       \`json:"id"\`
	Model   string       \`json:"model"\`
	Choices []ChatChoice \`json:"choices"\`
	Usage   *Usage       \`json:"usage,omitempty"\`
}

// One message of the conversation.
type ChatMessage struct {
	Role      string     \`json:"role"\`
	Content   *string    \`json:"content,omitempty"\`
	ToolCalls []ToolCall \`json:"tool_calls,omitempty"\`
}

// One embedded input.
type EmbeddingData struct {
	Embedding []float64 \`json:"embedding"\`
	Index     int64     \`json:"index"\`
}

// The body of POST /ai/embeddings.
type EmbeddingsRequest struct {
	Model *string \`json:"model,omitempty"\`
	Input any     \`json:"input"\`
}

// The body of POST /ai/embeddings.
type EmbeddingsResponse struct {
	Model string          \`json:"model"\`
	Data  []EmbeddingData \`json:"data"\`
}

// A concrete tool invocation returned by the model.
type ToolCall struct {
	Id        string \`json:"id"\`
	Name      string \`json:"name"\`
	Arguments string \`json:"arguments"\`
}

// A function the model may call (tool/function calling, decision 20).
type ToolDefinition struct {
	Name        string         \`json:"name"\`
	Description *string        \`json:"description,omitempty"\`
	Parameters  map[string]any \`json:"parameters,omitempty"\`
}

// Token accounting for a completion.
type Usage struct {
	PromptTokens     int64 \`json:"prompt_tokens"\`
	CompletionTokens int64 \`json:"completion_tokens"\`
	TotalTokens      int64 \`json:"total_tokens"\`
}

// A vector to store (upsert) or a stored vector's metadata.
type VectorRecord struct {
	Id       string         \`json:"id"\`
	Vector   []float64      \`json:"vector"\`
	Metadata map[string]any \`json:"metadata,omitempty"\`
}

// The body of POST /ai/vector-store/search.
type VectorStoreSearchRequest struct {
	Vector []float64 \`json:"vector"\`
	TopK   int64     \`json:"top_k,omitempty"\`
}

// The body of POST /ai/vector-store/search.
type VectorStoreSearchResponse struct {
	Results []VectorStoreSearchResult \`json:"results"\`
}

// One nearest-neighbour hit.
type VectorStoreSearchResult struct {
	Id       string         \`json:"id"\`
	Score    float64        \`json:"score"\`
	Metadata map[string]any \`json:"metadata,omitempty"\`
}

// The body of POST /ai/vector-store/upsert.
type VectorStoreUpsertRequest struct {
	Vectors []VectorRecord \`json:"vectors"\`
}

// The body of POST /ai/vector-store/upsert.
type VectorStoreUpsertResponse struct {
	Count int64 \`json:"count"\`
}

// HTTPError carries a non-2xx response from the AI service.
type HTTPError struct {
	Status int
	Body   string
}

func (e *HTTPError) Error() string {
	if e.Body == "" {
		return fmt.Sprintf("aiclient: %s", http.StatusText(e.Status))
	}
	return fmt.Sprintf("aiclient: %s: %s", http.StatusText(e.Status), e.Body)
}

// Client is a typed Go client over the committed openapi.ai.yaml.
type Client struct {
	baseURL string
	http    *http.Client
}

// NewClient wires a client to the AI service base URL, e.g.
// http://localhost:3200 (AI_SERVICE_URL).
func NewClient(baseURL string) *Client {
	return &Client{baseURL: strings.TrimSuffix(baseURL, "/"), http: &http.Client{Timeout: 30 * time.Second}}
}

// do performs one JSON request/response round-trip.
func (c *Client) do(ctx context.Context, method, path string, body, out any) error {
	var reader io.Reader
	if body != nil {
		raw, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("aiclient: marshal %s %s: %w", method, path, err)
		}
		reader = bytes.NewReader(raw)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, reader)
	if err != nil {
		return fmt.Errorf("aiclient: %s %s: %w", method, path, err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("aiclient: %s %s: %w", method, path, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		raw, _ := io.ReadAll(resp.Body)
		return &HTTPError{Status: resp.StatusCode, Body: strings.TrimSpace(string(raw))}
	}
	if out != nil {
		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {
			return fmt.Errorf("aiclient: decode %s %s: %w", method, path, err)
		}
	}
	return nil
}

// CHATCOMPLETIONS calls POST /ai/chat/completions.
func (c *Client) ChatCompletions(ctx context.Context, req ChatCompletionRequest) (*ChatCompletionResponse, error) {
	var out ChatCompletionResponse
	if err := c.do(ctx, http.MethodPost, "/ai/chat/completions", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// EMBEDDINGS calls POST /ai/embeddings.
func (c *Client) Embeddings(ctx context.Context, req EmbeddingsRequest) (*EmbeddingsResponse, error) {
	var out EmbeddingsResponse
	if err := c.do(ctx, http.MethodPost, "/ai/embeddings", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// VECTORSTOREUPSERT calls POST /ai/vector-store/upsert.
func (c *Client) VectorStoreUpsert(ctx context.Context, req VectorStoreUpsertRequest) (*VectorStoreUpsertResponse, error) {
	var out VectorStoreUpsertResponse
	if err := c.do(ctx, http.MethodPost, "/ai/vector-store/upsert", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// VECTORSTORESEARCH calls POST /ai/vector-store/search.
func (c *Client) VectorStoreSearch(ctx context.Context, req VectorStoreSearchRequest) (*VectorStoreSearchResponse, error) {
	var out VectorStoreSearchResponse
	if err := c.do(ctx, http.MethodPost, "/ai/vector-store/search", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
`;
}
function goClientReadme(): string {
  return `# clients/go — the generated Go client for the AI service

A stdlib-only Go client over the committed \`../openapi.ai.yaml\` — the
AI service's Python-generated spec (decision 9: Python is the
canonical side of the AI service's own contract). \`apps/api\` consumes
this client through a local \`go.mod\` replace:

    require starter/contract/ai-client v0.0.0
    replace starter/contract/ai-client => ../../packages/contract/clients/go

…and that is the ONLY way the Go api talks to apps/ai (decision 5: the
AI service is called by the Go api, never by the web app directly, and
never by raw HTTP in the api).

## Regenerating

The client is generated, never hand-edited:

1. Change the Python models in \`apps/ai/app/primitives/models.py\`.
2. \`task contract:generate\` — regenerates \`openapi.ai.yaml\` from the
   FastAPI app AND this client from the spec.
3. Commit the diff (the scaffold's tests tripwire this: the AI
   service's \`tests/test_contract.py\` proves the committed spec equals
   the live spec; \`test/generated-go.test.ts\` proves this client
   equals the generator's output).
`;
}
function generatedGoTestTs(): string {
  return `// test/generated-go.test.ts — proves the AI contract's
// Go-as-downstream rule holds in the scaffolded project (issue #16,
// decision 9/19 applied to the Python side): the committed Go client
// (clients/go/client.go) is byte-identical to what the committed
// generator produces from the committed openapi.ai.yaml. If the
// Python service's spec changes, \`task contract:generate\` must be run
// and its output committed — this test is the tripwire.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const contractDir = resolve(import.meta.dirname, '..');
const specPath = join(contractDir, 'openapi.ai.yaml');
const generator = join(contractDir, 'scripts/generate-go-client.mjs');
const committed = join(contractDir, 'clients/go/client.go');

describe('generated Go client is committed and up to date (issue #16, decision 9)', () => {
  it('regenerating from the committed openapi.ai.yaml changes nothing', () => {
    const out = mkdtempSync(join(tmpdir(), 'contract-go-regen-'));
    try {
      execFileSync(process.execPath, [generator, specPath, out], { stdio: 'pipe' });
      expect(
        readFileSync(join(out, 'client.go'), 'utf8'),
        'clients/go/client.go is stale — run \`task contract:generate\` and commit the diff',
      ).toBe(readFileSync(committed, 'utf8'));
    } finally {
      rmSync(out, { recursive: true, force: true });
    }
  });

  it('the client exposes the four composable primitives (decision 20)', () => {
    const client = readFileSync(committed, 'utf8');
    for (const m of ['ChatCompletions', 'Embeddings', 'VectorStoreUpsert', 'VectorStoreSearch']) {
      expect(client, \`client.go should expose \${m}\`).toContain(\`func (c *Client) \${m}(\`);
    }
  });
});
`;
}

// openapiApiYamlAi is the AI-on committed api partial: the base shape-4
// openapi.api.yaml PLUS the /ai proxy routes (issue #16). GENERATED by
// apps/api's cmd/specgen; the apps/api contract_test.go is the tripwire.
// Never hand-edit: change the Go structs and regenerate.
function openapiApiYamlAi(): string {
  return `components:
    schemas:
        ChatChoice:
            additionalProperties: false
            properties:
                finish_reason:
                    type: string
                index:
                    format: int64
                    type: integer
                message:
                    $ref: '#/components/schemas/ChatMessage'
            required:
                - index
                - message
            type: object
        ChatCompletionRequest:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/ChatCompletionRequest.json
                    format: uri
                    readOnly: true
                    type: string
                messages:
                    items:
                        $ref: '#/components/schemas/ChatMessage'
                    type:
                        - array
                        - "null"
                model:
                    type: string
                stream:
                    type: boolean
                temperature:
                    format: double
                    type: number
                tool_choice:
                    type: string
                tools:
                    items:
                        $ref: '#/components/schemas/ToolDefinition'
                    type:
                        - array
                        - "null"
            required:
                - messages
            type: object
        ChatCompletionResponse:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/ChatCompletionResponse.json
                    format: uri
                    readOnly: true
                    type: string
                choices:
                    items:
                        $ref: '#/components/schemas/ChatChoice'
                    type:
                        - array
                        - "null"
                id:
                    type: string
                model:
                    type: string
                usage:
                    $ref: '#/components/schemas/Usage'
            required:
                - id
                - model
                - choices
            type: object
        ChatMessage:
            additionalProperties: false
            properties:
                content:
                    type: string
                role:
                    type: string
                tool_calls:
                    items:
                        $ref: '#/components/schemas/ToolCall'
                    type:
                        - array
                        - "null"
            required:
                - role
            type: object
        EmbeddingData:
            additionalProperties: false
            properties:
                embedding:
                    items:
                        format: double
                        type: number
                    type:
                        - array
                        - "null"
                index:
                    format: int64
                    type: integer
            required:
                - embedding
                - index
            type: object
        EmbeddingsRequest:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/EmbeddingsRequest.json
                    format: uri
                    readOnly: true
                    type: string
                input: {}
                model:
                    type: string
            required:
                - input
            type: object
        EmbeddingsResponse:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/EmbeddingsResponse.json
                    format: uri
                    readOnly: true
                    type: string
                data:
                    items:
                        $ref: '#/components/schemas/EmbeddingData'
                    type:
                        - array
                        - "null"
                model:
                    type: string
            required:
                - model
                - data
            type: object
        ErrorDetail:
            additionalProperties: false
            properties:
                location:
                    description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
                    type: string
                message:
                    description: Error message text
                    type: string
                value:
                    description: The value at the given location
            type: object
        ErrorModel:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/ErrorModel.json
                    format: uri
                    readOnly: true
                    type: string
                detail:
                    description: A human-readable explanation specific to this occurrence of the problem.
                    examples:
                        - Property foo is required but is missing.
                    type: string
                errors:
                    description: Optional list of individual error details
                    items:
                        $ref: '#/components/schemas/ErrorDetail'
                    type:
                        - array
                        - "null"
                instance:
                    description: A URI reference that identifies the specific occurrence of the problem.
                    examples:
                        - https://example.com/error-log/abc123
                    format: uri
                    type: string
                status:
                    description: HTTP status code
                    examples:
                        - 400
                    format: int64
                    type: integer
                title:
                    description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
                    examples:
                        - Bad Request
                    type: string
                type:
                    default: about:blank
                    description: A URI reference to human-readable documentation for the error.
                    examples:
                        - https://example.com/errors/example
                    format: uri
                    type: string
            type: object
        Item:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/Item.json
                    format: uri
                    readOnly: true
                    type: string
                created_at:
                    format: date-time
                    type: string
                id:
                    type: string
                name:
                    maxLength: 200
                    type: string
            required:
                - id
                - name
                - created_at
            type: object
        ItemCreateInputBody:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/ItemCreateInputBody.json
                    format: uri
                    readOnly: true
                    type: string
                name:
                    description: Name of the item
                    maxLength: 200
                    minLength: 1
                    type: string
            required:
                - name
            type: object
        ToolCall:
            additionalProperties: false
            properties:
                arguments:
                    type: string
                id:
                    type: string
                name:
                    type: string
            required:
                - id
                - name
                - arguments
            type: object
        ToolDefinition:
            additionalProperties: false
            properties:
                description:
                    type: string
                name:
                    type: string
                parameters:
                    additionalProperties: {}
                    type: object
            required:
                - name
            type: object
        Usage:
            additionalProperties: false
            properties:
                completion_tokens:
                    format: int64
                    type: integer
                prompt_tokens:
                    format: int64
                    type: integer
                total_tokens:
                    format: int64
                    type: integer
            required:
                - prompt_tokens
                - completion_tokens
                - total_tokens
            type: object
        VectorRecord:
            additionalProperties: false
            properties:
                id:
                    type: string
                metadata:
                    additionalProperties: {}
                    type: object
                vector:
                    items:
                        format: double
                        type: number
                    type:
                        - array
                        - "null"
            required:
                - id
                - vector
            type: object
        VectorStoreSearchRequest:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/VectorStoreSearchRequest.json
                    format: uri
                    readOnly: true
                    type: string
                top_k:
                    format: int64
                    type: integer
                vector:
                    items:
                        format: double
                        type: number
                    type:
                        - array
                        - "null"
            required:
                - vector
            type: object
        VectorStoreSearchResponse:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/VectorStoreSearchResponse.json
                    format: uri
                    readOnly: true
                    type: string
                results:
                    items:
                        $ref: '#/components/schemas/VectorStoreSearchResult'
                    type:
                        - array
                        - "null"
            required:
                - results
            type: object
        VectorStoreSearchResult:
            additionalProperties: false
            properties:
                id:
                    type: string
                metadata:
                    additionalProperties: {}
                    type: object
                score:
                    format: double
                    type: number
            required:
                - id
                - score
            type: object
        VectorStoreUpsertRequest:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/VectorStoreUpsertRequest.json
                    format: uri
                    readOnly: true
                    type: string
                vectors:
                    items:
                        $ref: '#/components/schemas/VectorRecord'
                    type:
                        - array
                        - "null"
            required:
                - vectors
            type: object
        VectorStoreUpsertResponse:
            additionalProperties: false
            properties:
                $schema:
                    description: A URL to the JSON Schema for this object.
                    examples:
                        - https://example.com/schemas/VectorStoreUpsertResponse.json
                    format: uri
                    readOnly: true
                    type: string
                count:
                    format: int64
                    type: integer
            required:
                - count
            type: object
    securitySchemes:
        bearerAuth:
            bearerFormat: JWT
            description: A short-lived access token (decision 16), minted by apps/api-auth (the sole minter, decision 11); verified locally against its fetched-and-cached JWKS.
            scheme: bearer
            type: http
info:
    description: 'The scaffolded Go api: items demo behind a JWKS-verified Bearer gate (decision 13/11), plus the AI primitives proxied to the Python/FastAPI AI service (issue #16). Auth lives on apps/api-auth (the sole minter).'
    title: Starter API
    version: 0.1.0
openapi: 3.1.0
paths:
    /ai/chat/completions:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ChatCompletionRequest'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatCompletionResponse'
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            security:
                - bearerAuth: []
            summary: Chat completion (JSON form, proxied to the AI service)
            tags:
                - ai
    /ai/embeddings:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/EmbeddingsRequest'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/EmbeddingsResponse'
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            security:
                - bearerAuth: []
            summary: Embeddings (proxied to the AI service)
            tags:
                - ai
    /ai/vector-store/search:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/VectorStoreSearchRequest'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VectorStoreSearchResponse'
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            security:
                - bearerAuth: []
            summary: Search the AI service's VectorStore
            tags:
                - ai
    /ai/vector-store/upsert:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/VectorStoreUpsertRequest'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VectorStoreUpsertResponse'
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            security:
                - bearerAuth: []
            summary: Upsert vectors into the AI service's VectorStore
            tags:
                - ai
    /items:
        get:
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/Item'
                                type:
                                    - array
                                    - "null"
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            security:
                - bearerAuth: []
            summary: List items
            tags:
                - items
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ItemCreateInputBody'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
                    description: OK
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ErrorModel'
                    description: Error
            security:
                - bearerAuth: []
            summary: Create an item
            tags:
                - items
`;
}
// openapiMergedYamlAi is the AI-on merged spine (the merge of the api
// partial above + openapi.auth.yaml). Same generation pipeline as the base
// shape: scripts/merge-openapi.mjs, committed byte-identical; the contract
// package's test/generated.test.ts is the tripwire.
function openapiMergedYamlAi(): string {
  return `openapi: 3.1.0
info:
  description: "The scaffolded Go api: items demo behind a JWKS-verified Bearer gate (decision 13/11), plus the AI primitives proxied to the Python/FastAPI AI service (issue #16). Auth lives on apps/api-auth (the sole minter)."
  title: Starter API
  version: 0.1.0
paths:
  /.well-known/jwks.json:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JWKSDocument"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Serve the JSON Web Key Set (decision 11)
      tags:
        - jwks
  /auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthCredentialsInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthTokens"
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Log in and receive a token pair
      tags:
        - auth
  /auth/logout:
    post:
      parameters:
        - in: cookie
          name: refresh_token
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRefreshInputBody"
      responses:
        "204":
          description: No Content
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Revoke the refresh token and clear the cookie
      tags:
        - auth
  /auth/refresh:
    post:
      parameters:
        - in: cookie
          name: refresh_token
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRefreshInputBody"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthTokens"
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Rotate the refresh token and issue a new pair
      tags:
        - auth
  /auth/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRegisterInputBody"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthRegisterOutputBody"
          description: Created
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Register a new user
      tags:
        - auth
  /ai/chat/completions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatCompletionRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatCompletionResponse"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - bearerAuth: []
      summary: Chat completion (JSON form, proxied to the AI service)
      tags:
        - ai
  /ai/embeddings:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmbeddingsRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmbeddingsResponse"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - bearerAuth: []
      summary: Embeddings (proxied to the AI service)
      tags:
        - ai
  /ai/vector-store/search:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VectorStoreSearchRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VectorStoreSearchResponse"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - bearerAuth: []
      summary: Search the AI service's VectorStore
      tags:
        - ai
  /ai/vector-store/upsert:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VectorStoreUpsertRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VectorStoreUpsertResponse"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - bearerAuth: []
      summary: Upsert vectors into the AI service's VectorStore
      tags:
        - ai
  /items:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Item"
                type:
                  - array
                  - "null"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - bearerAuth: []
      summary: List items
      tags:
        - items
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemCreateInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - bearerAuth: []
      summary: Create an item
      tags:
        - items
components:
  schemas:
    AuthCredentialsInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthCredentialsInputBody.json
          format: uri
          readOnly: true
          type: string
        email:
          format: email
          maxLength: 256
          type: string
        password:
          maxLength: 256
          minLength: 1
          type: string
      required:
        - email
        - password
      type: object
    AuthRefreshInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthRefreshInputBody.json
          format: uri
          readOnly: true
          type: string
        refresh:
          type: string
      type: object
    AuthRegisterInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthRegisterInputBody.json
          format: uri
          readOnly: true
          type: string
        email:
          format: email
          maxLength: 256
          type: string
        password:
          maxLength: 256
          minLength: 8
          type: string
      required:
        - email
        - password
      type: object
    AuthRegisterOutputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthRegisterOutputBody.json
          format: uri
          readOnly: true
          type: string
        access:
          type: string
        refresh:
          type: string
        user:
          $ref: "#/components/schemas/AuthUser"
      required:
        - access
        - refresh
        - user
      type: object
    AuthTokens:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AuthTokens.json
          format: uri
          readOnly: true
          type: string
        access:
          type: string
        refresh:
          type: string
      required:
        - access
        - refresh
      type: object
    AuthUser:
      additionalProperties: false
      properties:
        email:
          type: string
        id:
          type: string
      required:
        - id
        - email
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type:
            - array
            - "null"
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          examples:
            - https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          examples:
            - 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
            - Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          examples:
            - https://example.com/errors/example
          format: uri
          type: string
      type: object
    JWK:
      additionalProperties: false
      properties:
        alg:
          type: string
        e:
          type: string
        kid:
          type: string
        kty:
          type: string
        n:
          type: string
        use:
          type: string
      required:
        - kty
        - kid
        - use
        - alg
        - n
        - e
      type: object
    JWKSDocument:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/JWKSDocument.json
          format: uri
          readOnly: true
          type: string
        keys:
          items:
            $ref: "#/components/schemas/JWK"
          type:
            - array
            - "null"
      required:
        - keys
      type: object
    ChatChoice:
      additionalProperties: false
      properties:
        finish_reason:
          type: string
        index:
          format: int64
          type: integer
        message:
          $ref: "#/components/schemas/ChatMessage"
      required:
        - index
        - message
      type: object
    ChatCompletionRequest:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ChatCompletionRequest.json
          format: uri
          readOnly: true
          type: string
        messages:
          items:
            $ref: "#/components/schemas/ChatMessage"
          type:
            - array
            - "null"
        model:
          type: string
        stream:
          type: boolean
        temperature:
          format: double
          type: number
        tool_choice:
          type: string
        tools:
          items:
            $ref: "#/components/schemas/ToolDefinition"
          type:
            - array
            - "null"
      required:
        - messages
      type: object
    ChatCompletionResponse:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ChatCompletionResponse.json
          format: uri
          readOnly: true
          type: string
        choices:
          items:
            $ref: "#/components/schemas/ChatChoice"
          type:
            - array
            - "null"
        id:
          type: string
        model:
          type: string
        usage:
          $ref: "#/components/schemas/Usage"
      required:
        - id
        - model
        - choices
      type: object
    ChatMessage:
      additionalProperties: false
      properties:
        content:
          type: string
        role:
          type: string
        tool_calls:
          items:
            $ref: "#/components/schemas/ToolCall"
          type:
            - array
            - "null"
      required:
        - role
      type: object
    EmbeddingData:
      additionalProperties: false
      properties:
        embedding:
          items:
            format: double
            type: number
          type:
            - array
            - "null"
        index:
          format: int64
          type: integer
      required:
        - embedding
        - index
      type: object
    EmbeddingsRequest:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/EmbeddingsRequest.json
          format: uri
          readOnly: true
          type: string
        input: {}
        model:
          type: string
      required:
        - input
      type: object
    EmbeddingsResponse:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/EmbeddingsResponse.json
          format: uri
          readOnly: true
          type: string
        data:
          items:
            $ref: "#/components/schemas/EmbeddingData"
          type:
            - array
            - "null"
        model:
          type: string
      required:
        - model
        - data
      type: object
    Item:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/Item.json
          format: uri
          readOnly: true
          type: string
        created_at:
          format: date-time
          type: string
        id:
          type: string
        name:
          maxLength: 200
          type: string
      required:
        - id
        - name
        - created_at
      type: object
    ItemCreateInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ItemCreateInputBody.json
          format: uri
          readOnly: true
          type: string
        name:
          description: Name of the item
          maxLength: 200
          minLength: 1
          type: string
      required:
        - name
      type: object
    ToolCall:
      additionalProperties: false
      properties:
        arguments:
          type: string
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
        - arguments
      type: object
    ToolDefinition:
      additionalProperties: false
      properties:
        description:
          type: string
        name:
          type: string
        parameters:
          additionalProperties: {}
          type: object
      required:
        - name
      type: object
    Usage:
      additionalProperties: false
      properties:
        completion_tokens:
          format: int64
          type: integer
        prompt_tokens:
          format: int64
          type: integer
        total_tokens:
          format: int64
          type: integer
      required:
        - prompt_tokens
        - completion_tokens
        - total_tokens
      type: object
    VectorRecord:
      additionalProperties: false
      properties:
        id:
          type: string
        metadata:
          additionalProperties: {}
          type: object
        vector:
          items:
            format: double
            type: number
          type:
            - array
            - "null"
      required:
        - id
        - vector
      type: object
    VectorStoreSearchRequest:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/VectorStoreSearchRequest.json
          format: uri
          readOnly: true
          type: string
        top_k:
          format: int64
          type: integer
        vector:
          items:
            format: double
            type: number
          type:
            - array
            - "null"
      required:
        - vector
      type: object
    VectorStoreSearchResponse:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/VectorStoreSearchResponse.json
          format: uri
          readOnly: true
          type: string
        results:
          items:
            $ref: "#/components/schemas/VectorStoreSearchResult"
          type:
            - array
            - "null"
      required:
        - results
      type: object
    VectorStoreSearchResult:
      additionalProperties: false
      properties:
        id:
          type: string
        metadata:
          additionalProperties: {}
          type: object
        score:
          format: double
          type: number
      required:
        - id
        - score
      type: object
    VectorStoreUpsertRequest:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/VectorStoreUpsertRequest.json
          format: uri
          readOnly: true
          type: string
        vectors:
          items:
            $ref: "#/components/schemas/VectorRecord"
          type:
            - array
            - "null"
      required:
        - vectors
      type: object
    VectorStoreUpsertResponse:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/VectorStoreUpsertResponse.json
          format: uri
          readOnly: true
          type: string
        count:
          format: int64
          type: integer
      required:
        - count
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: A short-lived access token (decision 16), minted by apps/api-auth (the sole minter, decision 11); verified locally against its fetched-and-cached JWKS.
      scheme: bearer
      type: http
`;
}
function clientTypesTsAi(): string {
  return `// GENERATED by scripts/generate-ts-client.mjs — do not edit by hand.
// Regenerate with \`task contract:generate\` after regenerating
// openapi.yaml from the Go structs (decision 19: Go is canonical,
// clients are downstream).

export interface AuthCredentialsInputBody {
  email: string;
  password: string;
}

export interface AuthRefreshInputBody {
  refresh?: string;
}

export interface AuthRegisterInputBody {
  email: string;
  password: string;
}

export interface AuthRegisterOutputBody {
  access: string;
  refresh: string;
  user: AuthUser;
}

export interface AuthTokens {
  access: string;
  refresh: string;
}

export interface AuthUser {
  email: string;
  id: string;
}

export interface ErrorDetail {
  location?: string;
  message?: string;
  value?: unknown;
}

export interface ErrorModel {
  detail?: string;
  errors?: ErrorDetail[];
  instance?: string;
  status?: number;
  title?: string;
  type?: string;
}

export interface JWK {
  alg: string;
  e: string;
  kid: string;
  kty: string;
  n: string;
  use: string;
}

export interface JWKSDocument {
  keys: JWK[];
}

export interface ChatChoice {
  finish_reason?: string;
  index: number;
  message: ChatMessage;
}

export interface ChatCompletionRequest {
  messages: ChatMessage[];
  model?: string;
  stream?: boolean;
  temperature?: number;
  tool_choice?: string;
  tools?: ToolDefinition[];
}

export interface ChatCompletionResponse {
  choices: ChatChoice[];
  id: string;
  model: string;
  usage?: Usage;
}

export interface ChatMessage {
  content?: string;
  role: string;
  tool_calls?: ToolCall[];
}

export interface EmbeddingData {
  embedding: number[];
  index: number;
}

export interface EmbeddingsRequest {
  input: unknown;
  model?: string;
}

export interface EmbeddingsResponse {
  data: EmbeddingData[];
  model: string;
}

export interface Item {
  created_at: string;
  id: string;
  name: string;
}

export interface ItemCreateInputBody {
  name: string;
}

export interface ToolCall {
  arguments: string;
  id: string;
  name: string;
}

export interface ToolDefinition {
  description?: string;
  name: string;
  parameters?: Record<string, unknown>;
}

export interface Usage {
  completion_tokens: number;
  prompt_tokens: number;
  total_tokens: number;
}

export interface VectorRecord {
  id: string;
  metadata?: Record<string, unknown>;
  vector: number[];
}

export interface VectorStoreSearchRequest {
  top_k?: number;
  vector: number[];
}

export interface VectorStoreSearchResponse {
  results: VectorStoreSearchResult[];
}

export interface VectorStoreSearchResult {
  id: string;
  metadata?: Record<string, unknown>;
  score: number;
}

export interface VectorStoreUpsertRequest {
  vectors: VectorRecord[];
}

export interface VectorStoreUpsertResponse {
  count: number;
}
`;
}
function clientTsAi(): string {
  return `// GENERATED by scripts/generate-ts-client.mjs — do not edit by hand.
// Regenerate with \`task contract:generate\` after regenerating
// openapi.yaml from the Go structs (decision 19: Go is canonical,
// clients are downstream).

import type {
  AuthCredentialsInputBody,
  AuthRefreshInputBody,
  AuthRegisterInputBody,
  AuthRegisterOutputBody,
  AuthTokens,
  ChatCompletionRequest,
  ChatCompletionResponse,
  EmbeddingsRequest,
  EmbeddingsResponse,
  Item,
  ItemCreateInputBody,
  VectorStoreSearchRequest,
  VectorStoreSearchResponse,
  VectorStoreUpsertRequest,
  VectorStoreUpsertResponse,
} from './types';

export interface ClientOptions {
  /** Base URL of the api, e.g. http://localhost:3000 */
  baseUrl: string;
  /** Returns the current access token (Bearer), if any. */
  getAccessToken?: () => string | null;
  /** Called when a request answers 401, e.g. to trigger a refresh. */
  onUnauthorized?: () => void;
  /** Fetch implementation override (defaults to global fetch). */
  fetch?: typeof fetch;
}

/** A typed fetch wrapper over the committed openapi.yaml (decision 19). */
export function createClient(options: ClientOptions) {
  const { baseUrl } = options;
  const doFetch = options.fetch ?? fetch;
  async function request<T>(method: string, path: string, body?: unknown, authenticated = false): Promise<T> {
    const headers: Record<string, string> = {};
    if (body !== undefined) headers['Content-Type'] = 'application/json';
    if (authenticated) {
      const token = options.getAccessToken?.() ?? null;
      if (token) headers['Authorization'] = \`Bearer \${token}\`;
    }
    const res = await doFetch(\`\${baseUrl}\${path}\`, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
      credentials: 'include',
    });
    if (res.status === 401) options.onUnauthorized?.();
    if (!res.ok) {
      let message = \`\${method} \${path} -> \${res.status}\`;
      try {
        const err = (await res.json()) as { detail?: string; title?: string };
        message = err.detail ?? err.title ?? message;
      } catch {
        // non-JSON error body; keep the status message
      }
      throw new Error(message);
    }
    if (res.status === 204) return undefined as T;
    return (await res.json()) as T;
  }

  return {

  auth: {
    /** POST /auth/login */
    login: async (input: AuthCredentialsInputBody) => request<AuthTokens>('post', '/auth/login', input),
    /** POST /auth/logout */
    logout: async (input: AuthRefreshInputBody) => request<void>('post', '/auth/logout', input),
    /** POST /auth/refresh */
    refresh: async (input: AuthRefreshInputBody) => request<AuthTokens>('post', '/auth/refresh', input),
    /** POST /auth/register */
    register: async (input: AuthRegisterInputBody) => request<AuthRegisterOutputBody>('post', '/auth/register', input),
  },
  ai: {
    /** POST /ai/chat/completions (requires Bearer access token) */
    chatCompletions: async (input: ChatCompletionRequest) => request<ChatCompletionResponse>('post', '/ai/chat/completions', input, true),
    /** POST /ai/embeddings (requires Bearer access token) */
    embeddings: async (input: EmbeddingsRequest) => request<EmbeddingsResponse>('post', '/ai/embeddings', input, true),
    /** POST /ai/vector-store/search (requires Bearer access token) */
    vectorStoreSearch: async (input: VectorStoreSearchRequest) => request<VectorStoreSearchResponse>('post', '/ai/vector-store/search', input, true),
    /** POST /ai/vector-store/upsert (requires Bearer access token) */
    vectorStoreUpsert: async (input: VectorStoreUpsertRequest) => request<VectorStoreUpsertResponse>('post', '/ai/vector-store/upsert', input, true),
  },
  items: {
    /** GET /items (requires Bearer access token) */
    list: async () => request<Item[]>('get', '/items', undefined, true),
    /** POST /items (requires Bearer access token) */
    create: async (input: ItemCreateInputBody) => request<Item>('post', '/items', input, true),
  },
};
}`;
}
function clientIndexTsAi(): string {
  return `// GENERATED by scripts/generate-ts-client.mjs — do not edit by hand.
// Regenerate with \`task contract:generate\` after regenerating
// openapi.yaml from the Go structs (decision 19: Go is canonical,
// clients are downstream).

export type {
  AuthCredentialsInputBody,
  AuthRefreshInputBody,
  AuthRegisterInputBody,
  AuthRegisterOutputBody,
  AuthTokens,
  AuthUser,
  ErrorDetail,
  ErrorModel,
  JWK,
  JWKSDocument,
  ChatChoice,
  ChatCompletionRequest,
  ChatCompletionResponse,
  ChatMessage,
  EmbeddingData,
  EmbeddingsRequest,
  EmbeddingsResponse,
  Item,
  ItemCreateInputBody,
  ToolCall,
  ToolDefinition,
  Usage,
  VectorRecord,
  VectorStoreSearchRequest,
  VectorStoreSearchResponse,
  VectorStoreSearchResult,
  VectorStoreUpsertRequest,
  VectorStoreUpsertResponse,
} from './types';
export { createClient, type ClientOptions } from './client';`;
}

// generatedTestTsAi is the AI-on version of the contract package's
// generated.test.ts (the base shape-4 one is overwritten): the
// tripwire now covers the /ai proxy surface of the merged spine.
function generatedTestTsAi(): string {
  return `// test/generated.test.ts — proves the Go-as-canonical rule holds in
// the scaffolded project (decision 19) for shape 4 + AI on
// (Go-microservices with the Python/FastAPI AI service, issue #16):
// every committed artifact in this package is byte-identical to what
// the generation pipeline produces. If a spec changes, \`task
// contract:generate\` must be run and its output committed — this
// file is the tripwire.
//
//   1. openapi.yaml == merge(openapi.api.yaml, openapi.auth.yaml)
//      (the partials are themselves tripwired by each service's
//      contract_test.go against its live spec; openapi.ai.yaml is
//      tripwired by apps/ai's tests/test_contract.py, and the Go
//      client generated from it by test/generated-go.test.ts)
//   2. the committed TS client == the generator's output from the
//      merged openapi.yaml
//   3. the client covers every route of the merged spec (except
//      well-known infra endpoints, which no client consumes)
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const contractDir = resolve(import.meta.dirname, '..');
const mergeScript = join(contractDir, 'scripts/merge-openapi.mjs');
const generator = join(contractDir, 'scripts/generate-ts-client.mjs');
const partials = {
  api: join(contractDir, 'openapi.api.yaml'),
  auth: join(contractDir, 'openapi.auth.yaml'),
};
const mergedSpec = join(contractDir, 'openapi.yaml');
const committed = {
  'types.ts': join(contractDir, 'src/types.ts'),
  'client.ts': join(contractDir, 'src/client.ts'),
  'index.ts': join(contractDir, 'src/index.ts'),
};

describe('the committed contract is generated, not hand-edited (decision 19, shape 4 + AI)', () => {
  it('the merged openapi.yaml equals the merge of the two committed partials', () => {
    const out = mkdtempSync(join(tmpdir(), 'contract-merge-'));
    try {
      execFileSync(process.execPath, [mergeScript, partials.api, partials.auth, join(out, 'merged.yaml')], {
        stdio: 'pipe',
      });
      expect(
        readFileSync(join(out, 'merged.yaml'), 'utf8'),
        \`openapi.yaml is stale — run \\\`task contract:generate\\\` and commit the diff\`,
      ).toBe(readFileSync(mergedSpec, 'utf8'));
    } finally {
      rmSync(out, { recursive: true, force: true });
    }
  });

  it('regenerating the TS client from the merged openapi.yaml changes nothing', () => {
    const out = mkdtempSync(join(tmpdir(), 'contract-regen-'));
    try {
      execFileSync(process.execPath, [generator, mergedSpec, out], { stdio: 'pipe' });
      for (const [name, committedPath] of Object.entries(committed)) {
        expect(readFileSync(join(out, name), 'utf8'), \`\${name} is stale — run \\\`task contract:generate\\\` and commit the diff\`)
          .toBe(readFileSync(committedPath, 'utf8'));
      }
    } finally {
      rmSync(out, { recursive: true, force: true });
    }
  });

  it('the client covers every route of the merged spec (well-known infra excluded)', () => {
    const client = readFileSync(committed['client.ts'], 'utf8');
    for (const ep of [
      '/items',
      '/auth/register',
      '/auth/login',
      '/auth/refresh',
      '/auth/logout',
      // Issue #16: the AI primitives reach the web through the api.
      '/ai/chat/completions',
      '/ai/embeddings',
      '/ai/vector-store/upsert',
      '/ai/vector-store/search',
    ]) {
      expect(client, \`client.ts should expose \${ep}\`).toContain(\`'\${ep}'\`);
    }
    // The JWKS endpoint is machine-to-machine infra consumed by the
    // api, not by generated clients — the generator skips well-known
    // paths, so the client must NOT contain it.
    expect(client).not.toContain('/.well-known');
    // The items routes are authenticated (Bearer) per the spec's
    // security requirement.
    expect(client).toMatch(/GET \\/items \\(requires Bearer access token\\)/);
  });
});
`;
}
export { openapiAiYaml, generateGoClientMjs, goClientGoMod, goClientGo, goClientReadme, generatedGoTestTs, openapiApiYamlAi, openapiMergedYamlAi, clientTypesTsAi, clientTsAi, clientIndexTsAi, generatedTestTsAi };
